const productsToCreate = [
  {
    description: "Organic Chicken Kibble",
    img_url: "organic_chicken_kibble.jpg",
    size: "Large",
    includes: "1 Bag of Organic Chicken Kibble",
    category: "Food",
    price: 39.99,
    stock: 120,
  },
  {
    description: "Beef Bone Chew",
    img_url: "beef_bone_chew.jpg",
    size: "Medium",
    includes: "1 Medium Beef Bone",
    category: "Treats/Bones",
    price: 8.99,
    stock: 200,
  },
  {
    description: "Nylon Rope Tug Toy",
    img_url: "nylon_rope_tug_toy.jpg",
    size: "Large",
    includes: "1 Large Rope Toy",
    category: "Toys",
    price: 12.49,
    stock: 175,
  },
  {
    description: "Pumpkin Food Topper",
    img_url: "pumpkin_food_topper.jpg",
    size: "Small",
    includes: "1 Bottle of Pumpkin Topper",
    category: "Food Toppers",
    price: 5.99,
    stock: 150,
  },
  {
    description: "Adjustable Nylon Collar - Red",
    img_url: "nylon_collar_red.jpg",
    size: "Medium",
    includes: "1 Medium Adjustable Collar",
    category: "Collars, Harnesses & Leashes",
    price: 14.99,
    stock: 90,
  },
  {
    description: "Memory Foam Dog Bed - XLarge",
    img_url: "foam_dog_bed_xl.jpg",
    size: "XLarge",
    includes: "1 XLarge Memory Foam Bed",
    category: "Beds",
    price: 79.99,
    stock: 40,
  },
  {
    description: "Double Bowl Feeder - Stainless Steel",
    img_url: "double_bowl_feeder.jpg",
    size: "Large",
    includes: "1 Stainless Steel Feeder Set",
    category: "Bowls",
    price: 24.99,
    stock: 110,
  },
  {
    description: "Gentle Shampoo with Oatmeal",
    img_url: "oatmeal_shampoo.jpg",
    size: "Medium",
    includes: "1 Bottle of Gentle Dog Shampoo",
    category: "Grooming",
    price: 10.99,
    stock: 180,
  },
  {
    description: "Puppy Chew Ring",
    img_url: "puppy_chew_ring.jpg",
    size: "Small",
    includes: "1 Small Chew Ring",
    category: "Toys",
    price: 6.49,
    stock: 200,
  },
  {
    description: "Crunchy Salmon Treats",
    img_url: "salmon_treats.jpg",
    size: "Small",
    includes: "1 Bag of Salmon Treats",
    category: "Treats/Bones",
    price: 7.99,
    stock: 175,
  },
  {
    description: "Freeze-Dried Liver Snacks",
    img_url: "liver_snacks.jpg",
    size: "Small",
    includes: "1 Bag of Liver Snacks",
    category: "Treats/Bones",
    price: 11.99,
    stock: 125,
  },
  {
    description: "Rubber Fetch Ball",
    img_url: "rubber_fetch_ball.jpg",
    size: "Large",
    includes: "1 Large Rubber Ball",
    category: "Toys",
    price: 9.99,
    stock: 190,
  },
  {
    description: "Beef and Veggie Kibble",
    img_url: "beef_veggie_kibble.jpg",
    size: "XLarge",
    includes: "1 XLarge Bag of Beef Kibble",
    category: "Food",
    price: 49.99,
    stock: 95,
  },
  {
    description: "Collapsible Travel Bowl",
    img_url: "travel_bowl.jpg",
    size: "Medium",
    includes: "1 Silicone Travel Bowl",
    category: "Bowls",
    price: 6.99,
    stock: 250,
  },
  {
    description: "Calming Bed with Faux Fur",
    img_url: "calming_bed.jpg",
    size: "Large",
    includes: "1 Cozy Calming Bed",
    category: "Beds",
    price: 69.99,
    stock: 70,
  },
  {
    description: "Grain-Free Lamb Topper",
    img_url: "lamb_topper.jpg",
    size: "Small",
    includes: "1 Pouch of Lamb Topper",
    category: "Food Toppers",
    price: 5.49,
    stock: 130,
  },
  {
    description: "Adjustable Harness - Black",
    img_url: "harness_black.jpg",
    size: "Large",
    includes: "1 Large Adjustable Harness",
    category: "Collars, Harnesses & Leashes",
    price: 19.99,
    stock: 105,
  },
  {
    description: "Steel Crate with Divider",
    img_url: "crate_divider.jpg",
    size: "XLarge",
    includes: "1 Steel Dog Crate with Divider",
    category: "Crates",
    price: 89.99,
    stock: 60,
  },
  {
    description: "Peanut Butter Filled Bone",
    img_url: "pb_filled_bone.jpg",
    size: "Medium",
    includes: "1 Medium Peanut Butter Bone",
    category: "Treats/Bones",
    price: 9.49,
    stock: 140,
  },
  {
    description: "Dual Handle Leash - Blue",
    img_url: "dual_leash_blue.jpg",
    size: "Medium",
    includes: "1 Dual Handle Leash",
    category: "Collars, Harnesses & Leashes",
    price: 17.99,
    stock: 100,
  },
  {
    description: "Stainless Steel Comb",
    img_url: "steel_comb.jpg",
    size: "Small",
    includes: "1 Grooming Comb",
    category: "Grooming",
    price: 8.99,
    stock: 85,
  },
  {
    description: "Deluxe Crate Mat",
    img_url: "crate_mat.jpg",
    size: "Medium",
    includes: "1 Deluxe Crate Mat",
    category: "Beds",
    price: 22.99,
    stock: 110,
  },
  {
    description: "Antler Chew - Natural",
    img_url: "antler_chew.jpg",
    size: "Large",
    includes: "1 Natural Antler",
    category: "Treats/Bones",
    price: 14.99,
    stock: 150,
  },
  {
    description: "Soft Grain-Free Biscuits",
    img_url: "grainfree_biscuits.jpg",
    size: "Small",
    includes: "1 Pack of Soft Biscuits",
    category: "Treats/Bones",
    price: 6.49,
    stock: 160,
  },
  {
    description: "Snuffle Feeding Mat",
    img_url: "snuffle_mat.jpg",
    size: "Medium",
    includes: "1 Snuffle Mat for Mental Stimulation",
    category: "Toys",
    price: 27.99,
    stock: 75,
  },
  {
    description: "Brush and Deshedding Tool",
    img_url: "brush_desh.jpg",
    size: "Large",
    includes: "1 Brush & Deshedder",
    category: "Grooming",
    price: 13.49,
    stock: 95,
  },
  {
    description: "Waterproof Food Mat",
    img_url: "food_mat.jpg",
    size: "Large",
    includes: "1 Waterproof Mat",
    category: "Bowls",
    price: 11.49,
    stock: 100,
  },
  {
    description: "Dehydrated Duck Treats",
    img_url: "duck_treats.jpg",
    size: "Medium",
    includes: "1 Bag of Duck Treats",
    category: "Treats/Bones",
    price: 12.99,
    stock: 135,
  },
  {
    description: "Goat Milk Topper Powder",
    img_url: "goatmilk_topper.jpg",
    size: "Small",
    includes: "1 Canister Goat Milk Topper",
    category: "Food Toppers",
    price: 9.99,
    stock: 115,
  },
  {
    description: "Interactive Treat Puzzle",
    img_url: "treat_puzzle.jpg",
    size: "Large",
    includes: "1 Dog Puzzle Toy",
    category: "Toys",
    price: 29.99,
    stock: 60,
  },
  {
    description: "Fish-Based Kibble Blend",
    img_url: "fish_kibble.jpg",
    size: "Medium",
    includes: "1 Bag of Fish Kibble",
    category: "Food",
    price: 34.99,
    stock: 120,
  },
  {
    description: "Crate Cover - Canvas",
    img_url: "crate_cover.jpg",
    size: "Large",
    includes: "1 Canvas Crate Cover",
    category: "Crates",
    price: 26.99,
    stock: 55,
  },
  {
    description: "Dental Chew Sticks",
    img_url: "dental_chews.jpg",
    size: "Medium",
    includes: "1 Pack of Dental Chews",
    category: "Treats/Bones",
    price: 8.49,
    stock: 190,
  },
  {
    description: "XL Memory Foam Crate Mat",
    img_url: "foam_crate_mat_xl.jpg",
    size: "XLarge",
    includes: "1 XL Crate Mat",
    category: "Beds",
    price: 59.99,
    stock: 45,
  },
  {
    description: "Water Fountain Bowl",
    img_url: "fountain_bowl.jpg",
    size: "Large",
    includes: "1 Automatic Water Bowl",
    category: "Bowls",
    price: 49.99,
    stock: 75,
  },
  {
    description: "Nail Clipper with Guard",
    img_url: "nail_clipper.jpg",
    size: "Small",
    includes: "1 Safety Nail Clipper",
    category: "Grooming",
    price: 7.99,
    stock: 150,
  },
  {
    description: "Turkey Jerky Treats",
    img_url: "turkey_jerky.jpg",
    size: "Medium",
    includes: "1 Bag of Turkey Jerky",
    category: "Treats/Bones",
    price: 10.99,
    stock: 130,
  },
  {
    description: "Plush Duck Toy with Squeaker",
    img_url: "plush_duck_toy.jpg",
    size: "Large",
    includes: "1 Plush Duck",
    category: "Toys",
    price: 11.99,
    stock: 140,
  },
  {
    description: "Salmon Oil Supplement",
    img_url: "salmon_oil.jpg",
    size: "Small",
    includes: "1 Bottle of Salmon Oil",
    category: "Food Toppers",
    price: 14.49,
    stock: 100,
  },
  {
    description: "Bacon Flavored Training Bites",
    img_url: "bacon_training_bites.jpg",
    size: "Small",
    includes: "1 Pack of Bacon Training Treats",
    category: "Treats/Bones",
    price: 6.49,
    stock: 180,
  },
  {
    description: "Eco-Friendly Dog Leash - Green",
    img_url: "eco_leash_green.jpg",
    size: "Medium",
    includes: "1 Eco-Friendly Leash",
    category: "Collars, Harnesses & Leashes",
    price: 13.99,
    stock: 95,
  },
  {
    description: "Tough Ballistic Chew Toy",
    img_url: "ballistic_chew_toy.jpg",
    size: "Large",
    includes: "1 Durable Ballistic Chew",
    category: "Toys",
    price: 17.99,
    stock: 120,
  },
  {
    description: "Organic Turkey Kibble",
    img_url: "organic_turkey_kibble.jpg",
    size: "Medium",
    includes: "1 Bag of Organic Turkey Kibble",
    category: "Food",
    price: 37.99,
    stock: 100,
  },
  {
    description: "Fleece Lined Harness - Gray",
    img_url: "fleece_harness_gray.jpg",
    size: "Large",
    includes: "1 Warm Fleece Harness",
    category: "Collars, Harnesses & Leashes",
    price: 21.99,
    stock: 85,
  },
  {
    description: "All-Natural Chewy Sticks",
    img_url: "chewy_sticks_natural.jpg",
    size: "Medium",
    includes: "1 Pack of Natural Chews",
    category: "Treats/Bones",
    price: 9.99,
    stock: 140,
  },
  {
    description: "Cooling Gel Mat",
    img_url: "cooling_gel_mat.jpg",
    size: "Large",
    includes: "1 Gel-Padded Cooling Mat",
    category: "Beds",
    price: 39.99,
    stock: 65,
  },
  {
    description: "Interactive Feeding Ball",
    img_url: "feeding_ball.jpg",
    size: "Medium",
    includes: "1 Treat Dispensing Ball",
    category: "Toys",
    price: 15.49,
    stock: 95,
  },
  {
    description: "High Protein Venison Kibble",
    img_url: "venison_kibble.jpg",
    size: "Large",
    includes: "1 High Protein Venison Bag",
    category: "Food",
    price: 44.99,
    stock: 90,
  },
  {
    description: "Bamboo Grooming Brush",
    img_url: "bamboo_brush.jpg",
    size: "Medium",
    includes: "1 Eco-Friendly Brush",
    category: "Grooming",
    price: 12.99,
    stock: 105,
  },
  {
    description: "Non-Slip Slow Feeder Bowl",
    img_url: "slow_feeder.jpg",
    size: "Large",
    includes: "1 Slow Feed Bowl",
    category: "Bowls",
    price: 19.99,
    stock: 125,
  },
  {
    description: "Cheddar Cheese Treat Bites",
    img_url: "cheddar_treats.jpg",
    size: "Small",
    includes: "1 Bag of Cheddar Bites",
    category: "Treats/Bones",
    price: 6.99,
    stock: 150,
  },
  {
    description: "Plush Alligator Tug Toy",
    img_url: "plush_alligator.jpg",
    size: "Medium",
    includes: "1 Squeaky Alligator Toy",
    category: "Toys",
    price: 13.49,
    stock: 110,
  },
  {
    description: "Biotin Skin & Coat Drops",
    img_url: "biotin_drops.jpg",
    size: "Small",
    includes: "1 Bottle of Biotin Drops",
    category: "Food Toppers",
    price: 14.99,
    stock: 100,
  },
  {
    description: "Heavy Duty Crate - Black",
    img_url: "heavy_duty_crate.jpg",
    size: "XLarge",
    includes: "1 Reinforced Dog Crate",
    category: "Crates",
    price: 119.99,
    stock: 40,
  },
  {
    description: "Lamb Sausage Bites",
    img_url: "lamb_sausage.jpg",
    size: "Small",
    includes: "1 Bag of Sausage Treats",
    category: "Treats/Bones",
    price: 10.49,
    stock: 130,
  },
  {
    description: "Adjustable Leash - Purple",
    img_url: "leash_purple.jpg",
    size: "Medium",
    includes: "1 Adjustable Dog Leash",
    category: "Collars, Harnesses & Leashes",
    price: 14.49,
    stock: 110,
  },
  {
    description: "Deep Clean Ear Wash",
    img_url: "ear_wash.jpg",
    size: "Small",
    includes: "1 Bottle of Dog Ear Cleaner",
    category: "Grooming",
    price: 11.49,
    stock: 85,
  },
  {
    description: "Hypoallergenic Duck Kibble",
    img_url: "hypo_duck_kibble.jpg",
    size: "Large",
    includes: "1 Hypoallergenic Duck Blend",
    category: "Food",
    price: 42.99,
    stock: 95,
  },
  {
    description: "Coconut Oil Topper",
    img_url: "coconut_topper.jpg",
    size: "Small",
    includes: "1 Jar of Coconut Topper",
    category: "Food Toppers",
    price: 9.99,
    stock: 125,
  },
  {
    description: "Ultra Plush Cuddler Bed",
    img_url: "plush_cuddler.jpg",
    size: "Large",
    includes: "1 Cuddler-Style Bed",
    category: "Beds",
    price: 74.99,
    stock: 70,
  },
  {
    description: "Heavy Duty Nail Grinder",
    img_url: "nail_grinder.jpg",
    size: "Medium",
    includes: "1 Electric Nail Grinder",
    category: "Grooming",
    price: 22.49,
    stock: 60,
  },
  {
    description: "Durable Crate Pad - Tan",
    img_url: "crate_pad_tan.jpg",
    size: "Medium",
    includes: "1 Crate Comfort Pad",
    category: "Beds",
    price: 27.49,
    stock: 90,
  },
  {
    description: "Puppy Starter Toy Set",
    img_url: "puppy_toy_set.jpg",
    size: "Small",
    includes: "1 Set of 3 Toys",
    category: "Toys",
    price: 18.99,
    stock: 130,
  },
  {
    description: "Natural Apple & Chicken Treats",
    img_url: "apple_chicken_treats.jpg",
    size: "Small",
    includes: "1 Bag of Fruit + Meat Bites",
    category: "Treats/Bones",
    price: 7.99,
    stock: 160,
  },
  {
    description: "Portable Water Bottle",
    img_url: "portable_water.jpg",
    size: "Medium",
    includes: "1 Travel Hydration Bottle",
    category: "Bowls",
    price: 12.49,
    stock: 140,
  },
  {
    description: "Reflective Dog Harness",
    img_url: "reflective_harness.jpg",
    size: "Large",
    includes: "1 Safety Reflective Harness",
    category: "Collars, Harnesses & Leashes",
    price: 19.49,
    stock: 100,
  },
  {
    description: "Grain-Free Salmon Jerky",
    img_url: "grainfree_salmon_jerky.jpg",
    size: "Small",
    includes: "1 Bag of Jerky Bites",
    category: "Treats/Bones",
    price: 8.99,
    stock: 150,
  },
  {
    description: "Mesh Travel Crate",
    img_url: "mesh_crate.jpg",
    size: "Medium",
    includes: "1 Lightweight Travel Crate",
    category: "Crates",
    price: 59.99,
    stock: 55,
  },
  {
    description: "Pumpkin Spice Food Topper",
    img_url: "pumpkin_spice_topper.jpg",
    size: "Small",
    includes: "1 Bottle of Pumpkin Spice Mix",
    category: "Food Toppers",
    price: 6.99,
    stock: 120,
  },
  {
    description: "Slicker Brush with Grip Handle",
    img_url: "slicker_brush.jpg",
    size: "Medium",
    includes: "1 Slicker Brush",
    category: "Grooming",
    price: 9.49,
    stock: 100,
  },
  {
    description: "Stuffed Bear Chew Toy",
    img_url: "stuffed_bear.jpg",
    size: "Large",
    includes: "1 Durable Bear Plush",
    category: "Toys",
    price: 14.99,
    stock: 110,
  },
  {
    description: "Grain-Free Duck Kibble",
    img_url: "grainfree_duck.jpg",
    size: "XLarge",
    includes: "1 Large Bag of Duck Food",
    category: "Food",
    price: 46.99,
    stock: 80,
  },
  {
    description: "Cooling Bandana - Blue",
    img_url: "cooling_bandana.jpg",
    size: "Small",
    includes: "1 Cooling Dog Bandana",
    category: "Grooming",
    price: 7.99,
    stock: 75,
  },
  {
    description: "Steel Food Scoop",
    img_url: "steel_scoop.jpg",
    size: "Medium",
    includes: "1 Food Measuring Scoop",
    category: "Bowls",
    price: 5.49,
    stock: 125,
  },
  {
    description: "Hide & Seek Puzzle Mat",
    img_url: "puzzle_mat.jpg",
    size: "Large",
    includes: "1 Mat with Hidden Compartments",
    category: "Toys",
    price: 24.99,
    stock: 90,
  },
  {
    description: "Calming Aid Soft Chews",
    img_url: "calming_soft_chews.jpg",
    size: "Small",
    includes: "1 Pack of Chews",
    category: "Food Toppers",
    price: 12.49,
    stock: 140,
  },
  {
    description: "Canvas Toy Storage Bin",
    img_url: "storage_bin.jpg",
    size: "Medium",
    includes: "1 Dog Toy Storage",
    category: "Toys",
    price: 18.49,
    stock: 60,
  },
  {
    description: "Deluxe Hair Remover Roller",
    img_url: "hair_remover.jpg",
    size: "Small",
    includes: "1 Fur Remover Roller",
    category: "Grooming",
    price: 8.49,
    stock: 150,
  },
  {
    description: "Grain-Free Chicken & Sweet Potato",
    img_url: "chicken_sweet_kibble.jpg",
    size: "Large",
    includes: "1 Grain-Free Dog Food Bag",
    category: "Food",
    price: 39.49,
    stock: 95,
  },
  {
    description: "Double Handle Traffic Leash",
    img_url: "traffic_leash.jpg",
    size: "Large",
    includes: "1 Dual-Handled Leash",
    category: "Collars, Harnesses & Leashes",
    price: 15.99,
    stock: 100,
  },
  {
    description: "Chew-Proof Dog Crate",
    img_url: "chewproof_crate.jpg",
    size: "XLarge",
    includes: "1 Reinforced Metal Crate",
    category: "Crates",
    price: 134.99,
    stock: 35,
  },
  {
    description: "Rubber Tug Ring Toy",
    img_url: "rubber_tug_ring.jpg",
    size: "Medium",
    includes: "1 Rubber Tug Ring",
    category: "Toys",
    price: 11.49,
    stock: 120,
  },
  {
    description: "Air-Dried Beef Liver Treats",
    img_url: "beef_liver_treats.jpg",
    size: "Small",
    includes: "1 Bag of Beef Liver Bites",
    category: "Treats/Bones",
    price: 8.49,
    stock: 140,
  },
  {
    description: "Raised Double Bowl Stand",
    img_url: "double_bowl_stand.jpg",
    size: "Large",
    includes: "1 Elevated Bowl Stand with 2 Bowls",
    category: "Bowls",
    price: 39.99,
    stock: 70,
  },
  {
    description: "Multi-Surface Paw Wipes",
    img_url: "paw_wipes.jpg",
    size: "Medium",
    includes: "1 Pack of 50 Wipes",
    category: "Grooming",
    price: 6.99,
    stock: 200,
  },
  {
    description: "Wool Felt Squeaky Ball",
    img_url: "wool_squeaky_ball.jpg",
    size: "Small",
    includes: "1 Wool Felt Toy Ball",
    category: "Toys",
    price: 9.49,
    stock: 100,
  },
  {
    description: "Freeze-Dried Raw Chicken",
    img_url: "raw_chicken.jpg",
    size: "Medium",
    includes: "1 Bag of Freeze-Dried Chicken",
    category: "Food",
    price: 28.99,
    stock: 90,
  },
  {
    description: "Snout Soother Balm",
    img_url: "snout_balm.jpg",
    size: "Small",
    includes: "1 Tin of Snout Balm",
    category: "Grooming",
    price: 7.99,
    stock: 110,
  },
  {
    description: "XL Soft-Sided Travel Carrier",
    img_url: "soft_travel_carrier.jpg",
    size: "XLarge",
    includes: "1 Soft-Sided Travel Crate",
    category: "Crates",
    price: 72.99,
    stock: 40,
  },
  {
    description: "Bacon & Apple Dental Chews",
    img_url: "bacon_apple_dental.jpg",
    size: "Medium",
    includes: "1 Pack of Dental Chews",
    category: "Treats/Bones",
    price: 10.99,
    stock: 130,
  },
  {
    description: "Foam Step Bed Ramp",
    img_url: "bed_ramp.jpg",
    size: "Large",
    includes: "1 Foam Pet Ramp",
    category: "Beds",
    price: 64.99,
    stock: 45,
  },
  {
    description: "Stylish Dog Bandana Pack",
    img_url: "bandana_pack.jpg",
    size: "Small",
    includes: "1 Pack of 3 Bandanas",
    category: "Grooming",
    price: 14.49,
    stock: 120,
  },
  {
    description: "Dog Birthday Toy Set",
    img_url: "birthday_toy_set.jpg",
    size: "Medium",
    includes: "1 Birthday Hat & Toy Set",
    category: "Toys",
    price: 18.99,
    stock: 75,
  },
  {
    description: "Hydrating Chicken Topper",
    img_url: "hydrating_chicken_topper.jpg",
    size: "Small",
    includes: "1 Pouch of Wet Chicken Topper",
    category: "Food Toppers",
    price: 6.49,
    stock: 130,
  },
  {
    description: "Reflective Collar - Red",
    img_url: "reflective_collar_red.jpg",
    size: "Medium",
    includes: "1 Reflective Dog Collar",
    category: "Collars, Harnesses & Leashes",
    price: 13.49,
    stock: 100,
  },
  {
    description: "Pumpkin Digestive Chews",
    img_url: "pumpkin_chews.jpg",
    size: "Small",
    includes: "1 Pack of Digestive Aids",
    category: "Food Toppers",
    price: 9.49,
    stock: 115,
  },
  {
    description: "Detangler Spray",
    img_url: "detangler_spray.jpg",
    size: "Small",
    includes: "1 Bottle of Coat Detangler",
    category: "Grooming",
    price: 8.99,
    stock: 90,
  },
  {
    description: "Wood Frame Orthopedic Bed",
    img_url: "wood_frame_bed.jpg",
    size: "XLarge",
    includes: "1 Wooden Orthopedic Dog Bed",
    category: "Beds",
    price: 98.99,
    stock: 30,
  },
  {
    description: "Tough Knot Rope Toy",
    img_url: "knot_rope_toy.jpg",
    size: "Large",
    includes: "1 Durable Rope Toy",
    category: "Toys",
    price: 12.99,
    stock: 150,
  },
  {
    description: "Shed Control Shampoo",
    img_url: "shed_shampoo.jpg",
    size: "Large",
    includes: "1 Bottle of Anti-Shed Shampoo",
    category: "Grooming",
    price: 10.99,
    stock: 95,
  },
  {
    description: "Grain-Free Turkey Stew",
    img_url: "turkey_stew.jpg",
    size: "Medium",
    includes: "1 Can of Turkey Stew",
    category: "Food",
    price: 3.99,
    stock: 200,
  },
  {
    description: "Heavy-Duty Waterproof Collar",
    img_url: "waterproof_collar.jpg",
    size: "Large",
    includes: "1 Waterproof Collar",
    category: "Collars, Harnesses & Leashes",
    price: 16.99,
    stock: 85,
  },
  {
    description: "Beef & Sweet Potato Topper",
    img_url: "beef_sweet_topper.jpg",
    size: "Small",
    includes: "1 Pouch of Wet Topper",
    category: "Food Toppers",
    price: 6.99,
    stock: 140,
  },
  {
    description: "Peanut Butter Chew Rings",
    img_url: "pb_chew_rings.jpg",
    size: "Medium",
    includes: "1 Pack of 5 Chew Rings",
    category: "Treats/Bones",
    price: 8.49,
    stock: 160,
  },
  {
    description: "Cooling Memory Foam Bed",
    img_url: "cooling_memory_bed.jpg",
    size: "Large",
    includes: "1 Cooling Dog Bed",
    category: "Beds",
    price: 89.99,
    stock: 50,
  },
  {
    description: "Car Seatbelt Harness",
    img_url: "seatbelt_harness.jpg",
    size: "Medium",
    includes: "1 Adjustable Seatbelt Harness",
    category: "Collars, Harnesses & Leashes",
    price: 19.49,
    stock: 70,
  },
  {
    description: "Rawhide-Free Dental Rolls",
    img_url: "dental_rolls.jpg",
    size: "Large",
    includes: "1 Pack of Dental Chews",
    category: "Treats/Bones",
    price: 11.49,
    stock: 130,
  },
  {
    description: "High-Fiber Kibble Blend",
    img_url: "highfiber_kibble.jpg",
    size: "Large",
    includes: "1 Bag of High-Fiber Dog Food",
    category: "Food",
    price: 36.99,
    stock: 90,
  },
  {
    description: "3-in-1 Grooming Tool",
    img_url: "3in1_grooming.jpg",
    size: "Medium",
    includes: "Brush, Comb & Deshedder",
    category: "Grooming",
    price: 17.49,
    stock: 80,
  },
  {
    description: "Trail Mix Crunch Treats",
    img_url: "trail_mix_treats.jpg",
    size: "Small",
    includes: "1 Bag of Mixed Crunch Treats",
    category: "Treats/Bones",
    price: 7.99,
    stock: 145,
  },
  {
    description: "Heavyweight Ceramic Bowl",
    img_url: "ceramic_bowl.jpg",
    size: "Large",
    includes: "1 Ceramic Bowl",
    category: "Bowls",
    price: 16.49,
    stock: 60,
  },
  {
    description: "Hiking Collar with Reflector",
    img_url: "hiking_collar.jpg",
    size: "Large",
    includes: "1 High-Durability Collar",
    category: "Collars, Harnesses & Leashes",
    price: 14.99,
    stock: 95,
  },
  {
    description: "Paw Wax Balm",
    img_url: "paw_wax.jpg",
    size: "Small",
    includes: "1 Tin of Protective Wax",
    category: "Grooming",
    price: 6.99,
    stock: 120,
  },
  {
    description: "Meaty Chews Variety Pack",
    img_url: "meaty_chews_variety.jpg",
    size: "Medium",
    includes: "1 Mixed Pack of Chews",
    category: "Treats/Bones",
    price: 12.49,
    stock: 110,
  },
  {
    description: "Organic Quinoa & Veggie Kibble",
    img_url: "quinoa_kibble.jpg",
    size: "Medium",
    includes: "1 Bag of Veggie Blend Food",
    category: "Food",
    price: 33.99,
    stock: 85,
  },
  {
    description: "Orthopedic Egg Crate Mattress",
    img_url: "egg_crate_bed.jpg",
    size: "XLarge",
    includes: "1 Therapeutic Bed",
    category: "Beds",
    price: 94.49,
    stock: 40,
  },
  {
    description: "Safety Lock Grooming Clippers",
    img_url: "grooming_clippers.jpg",
    size: "Small",
    includes: "1 Pair of Clippers",
    category: "Grooming",
    price: 10.99,
    stock: 100,
  },
  {
    description: "Bison Jerky Treat Sticks",
    img_url: "bison_jerky.jpg",
    size: "Small",
    includes: "1 Pack of Jerky Treats",
    category: "Treats/Bones",
    price: 8.99,
    stock: 135,
  },
  {
    description: "Silicone Collapsible Travel Bowl",
    img_url: "collapsible_bowl.jpg",
    size: "Medium",
    includes: "1 Foldable Travel Bowl",
    category: "Bowls",
    price: 7.49,
    stock: 145,
  },
  {
    description: "Multi-Layer Puzzle Feeder",
    img_url: "puzzle_feeder.jpg",
    size: "Large",
    includes: "1 Puzzle Feeder",
    category: "Toys",
    price: 23.49,
    stock: 70,
  },
  {
    description: "Grain-Free Salmon Kibble",
    img_url: "salmon_kibble.jpg",
    size: "Large",
    includes: "1 Bag of Grain-Free Kibble",
    category: "Food",
    price: 37.99,
    stock: 85,
  },
  {
    description: "Portable Water Bottle Dispenser",
    img_url: "portable_water_bottle.jpg",
    size: "Small",
    includes: "1 Leakproof Water Dispenser",
    category: "Bowls",
    price: 12.49,
    stock: 100,
  },
  {
    description: "Heavy-Duty Training Harness",
    img_url: "training_harness.jpg",
    size: "XLarge",
    includes: "1 No-Pull Training Harness",
    category: "Collars, Harnesses & Leashes",
    price: 29.99,
    stock: 60,
  },
  {
    description: "Lamb & Rice Soft Bites",
    img_url: "lamb_rice_bites.jpg",
    size: "Medium",
    includes: "1 Pack of Lamb Soft Treats",
    category: "Treats/Bones",
    price: 9.49,
    stock: 110,
  },
  {
    description: "Plush Squeaky Elephant Toy",
    img_url: "squeaky_elephant.jpg",
    size: "Medium",
    includes: "1 Plush Elephant Toy",
    category: "Toys",
    price: 10.99,
    stock: 85,
  },
  {
    description: "Quick-Dry Dog Bathrobe",
    img_url: "dog_bathrobe.jpg",
    size: "Large",
    includes: "1 Absorbent Bathrobe",
    category: "Grooming",
    price: 19.99,
    stock: 55,
  },
  {
    description: "Antler Chew Split",
    img_url: "antler_chew.jpg",
    size: "Large",
    includes: "1 Split Elk Antler",
    category: "Treats/Bones",
    price: 13.99,
    stock: 75,
  },
  {
    description: "Premium Wooden Crate",
    img_url: "wooden_crate.jpg",
    size: "XLarge",
    includes: "1 Wooden Style Crate",
    category: "Crates",
    price: 149.99,
    stock: 25,
  },
  {
    description: "Dental Sticks with Mint",
    img_url: "mint_dental_sticks.jpg",
    size: "Small",
    includes: "1 Pack of Mint Dental Sticks",
    category: "Treats/Bones",
    price: 7.49,
    stock: 120,
  },
  {
    description: "Organic Skin & Coat Oil",
    img_url: "skin_coat_oil.jpg",
    size: "Medium",
    includes: "1 Bottle of Supplement Oil",
    category: "Food Toppers",
    price: 21.99,
    stock: 40,
  },
  {
    description: "Sisal Rope Tug & Toss Ball",
    img_url: "sisal_tug_toy.jpg",
    size: "Large",
    includes: "1 Sisal Rope Ball",
    category: "Toys",
    price: 14.99,
    stock: 70,
  },
  {
    description: "Washable Pee Pad Set",
    img_url: "pee_pad_set.jpg",
    size: "Medium",
    includes: "Set of 2 Washable Pads",
    category: "Beds",
    price: 26.99,
    stock: 90,
  },
  {
    description: "Beef Bone Broth Topper",
    img_url: "bone_broth_topper.jpg",
    size: "Small",
    includes: "1 Jar of Bone Broth",
    category: "Food Toppers",
    price: 8.99,
    stock: 65,
  },
  {
    description: "Rope Ball with Handle",
    img_url: "rope_ball_handle.jpg",
    size: "Medium",
    includes: "1 Rope Ball Tug Toy",
    category: "Toys",
    price: 11.99,
    stock: 95,
  },
  {
    description: "No-Rinse Foam Shampoo",
    img_url: "foam_shampoo.jpg",
    size: "Small",
    includes: "1 Bottle of Foam Shampoo",
    category: "Grooming",
    price: 9.99,
    stock: 100,
  },
  {
    description: "Multi-Compartment Feeder",
    img_url: "compartment_feeder.jpg",
    size: "Large",
    includes: "1 Slow-Feed Puzzle Bowl",
    category: "Bowls",
    price: 22.49,
    stock: 60,
  },
  {
    description: "Grain-Free Duck Jerky",
    img_url: "duck_jerky.jpg",
    size: "Medium",
    includes: "1 Pack of Duck Jerky",
    category: "Treats/Bones",
    price: 10.49,
    stock: 100,
  },
  {
    description: "3-Level Chew Tower Toy",
    img_url: "chew_tower.jpg",
    size: "Large",
    includes: "1 Chew Toy Tower",
    category: "Toys",
    price: 17.99,
    stock: 80,
  },
  {
    description: "Adjustable Leather Collar",
    img_url: "leather_collar.jpg",
    size: "Large",
    includes: "1 Real Leather Collar",
    category: "Collars, Harnesses & Leashes",
    price: 24.99,
    stock: 65,
  },
  {
    description: "Beef & Quinoa Pouch Meal",
    img_url: "beef_quinoa_meal.jpg",
    size: "Medium",
    includes: "1 Ready-to-Eat Meal Pouch",
    category: "Food",
    price: 6.99,
    stock: 85,
  },
  {
    description: "Vet-Approved Ear Wipes",
    img_url: "ear_wipes.jpg",
    size: "Small",
    includes: "1 Pack of 30 Wipes",
    category: "Grooming",
    price: 7.49,
    stock: 90,
  },
  {
    description: "Travel Bowl Duo Set",
    img_url: "bowl_duo_set.jpg",
    size: "Small",
    includes: "2 Stackable Bowls with Lid",
    category: "Bowls",
    price: 15.99,
    stock: 75,
  },
  {
    description: "Slicker Brush with Grip",
    img_url: "slicker_brush.jpg",
    size: "Medium",
    includes: "1 Grip-Handled Brush",
    category: "Grooming",
    price: 12.99,
    stock: 85,
  },
  {
    description: "Chicken & Pea Kibble Blend",
    img_url: "chicken_pea_kibble.jpg",
    size: "Large",
    includes: "1 Bag of Dry Kibble",
    category: "Food",
    price: 34.49,
    stock: 100,
  },
  {
    description: "Floating Fetch Stick",
    img_url: "floating_fetch_stick.jpg",
    size: "Large",
    includes: "1 Floating Toy Stick",
    category: "Toys",
    price: 13.99,
    stock: 95,
  },
  {
    description: "Organic Salmon Oil Topper",
    img_url: "salmon_oil_topper.jpg",
    size: "Medium",
    includes: "1 Pump Bottle of Salmon Oil",
    category: "Food Toppers",
    price: 19.49,
    stock: 80,
  },
  {
    description: "Reflective Harness Vest",
    img_url: "reflective_vest.jpg",
    size: "Medium",
    includes: "1 Breathable Mesh Vest",
    category: "Collars, Harnesses & Leashes",
    price: 18.99,
    stock: 75,
  },
  {
    description: "Car Hammock Seat Cover",
    img_url: "car_seat_cover.jpg",
    size: "XLarge",
    includes: "1 Waterproof Hammock Cover",
    category: "Crates",
    price: 42.99,
    stock: 50,
  },
  {
    description: "Lamb & Carrot Soft Bites",
    img_url: "lamb_carrot_bites.jpg",
    size: "Small",
    includes: "1 Bag of Soft Training Bites",
    category: "Treats/Bones",
    price: 8.99,
    stock: 110,
  },
  {
    description: "Grooming Glove Mitt",
    img_url: "grooming_mitt.jpg",
    size: "Large",
    includes: "1 Hair-Removing Glove",
    category: "Grooming",
    price: 10.49,
    stock: 95,
  },
  {
    description: "Dual Handle Jogging Leash",
    img_url: "jogging_leash.jpg",
    size: "Large",
    includes: "1 Stretchable Jog Leash",
    category: "Collars, Harnesses & Leashes",
    price: 16.99,
    stock: 65,
  },
  {
    description: "Breathable Cooling Bed",
    img_url: "cooling_bed.jpg",
    size: "XLarge",
    includes: "1 Elevated Cooling Bed",
    category: "Beds",
    price: 82.99,
    stock: 40,
  },
  {
    description: "Venison Stick Chews",
    img_url: "venison_sticks.jpg",
    size: "Medium",
    includes: "1 Pack of 8 Sticks",
    category: "Treats/Bones",
    price: 11.49,
    stock: 100,
  },
  {
    description: "Crinkle Plush Gator Toy",
    img_url: "gator_crinkle_toy.jpg",
    size: "Medium",
    includes: "1 Crinkly Plush Toy",
    category: "Toys",
    price: 12.49,
    stock: 80,
  },
  {
    description: "Meal Topper Powder Mix",
    img_url: "meal_topper_powder.jpg",
    size: "Small",
    includes: "1 Jar of Mix-In Powder",
    category: "Food Toppers",
    price: 9.99,
    stock: 70,
  },
  {
    description: "Snuffle Mat Puzzle Pad",
    img_url: "snuffle_mat.jpg",
    size: "Large",
    includes: "1 Interactive Feeding Mat",
    category: "Toys",
    price: 25.99,
    stock: 60,
  },
  {
    description: "Stainless Steel Bowl Set",
    img_url: "ss_bowl_set.jpg",
    size: "Medium",
    includes: "2 Stainless Bowls + Stand",
    category: "Bowls",
    price: 28.49,
    stock: 75,
  },
  {
    description: "Dog Rain Jacket - Yellow",
    img_url: "rain_jacket_yellow.jpg",
    size: "Large",
    includes: "1 Waterproof Rain Coat",
    category: "Grooming",
    price: 29.99,
    stock: 55,
  },
  {
    description: "Allergen-Free Chicken Kibble",
    img_url: "allergen_free_kibble.jpg",
    size: "Large",
    includes: "1 Bag of Hypoallergenic Food",
    category: "Food",
    price: 38.99,
    stock: 70,
  },
  {
    description: "XL Supportive Dog Mattress",
    img_url: "xl_mattress_bed.jpg",
    size: "XLarge",
    includes: "1 Supportive Foam Bed",
    category: "Beds",
    price: 109.99,
    stock: 35,
  },
  {
    description: "Chew-Resistant Dog Bone",
    img_url: "resistant_bone.jpg",
    size: "Large",
    includes: "1 Durable Chew Bone",
    category: "Treats/Bones",
    price: 19.99,
    stock: 45,
  },
  {
    description: "Stylish Denim Dog Jacket",
    img_url: "denim_jacket.jpg",
    size: "Medium",
    includes: "1 Denim Jacket",
    category: "Grooming",
    price: 24.99,
    stock: 50,
  },
  {
    description: "Interactive Fetch Ball Launcher",
    img_url: "fetch_ball_launcher.jpg",
    size: "Large",
    includes: "1 Ball Launcher",
    category: "Toys",
    price: 39.99,
    stock: 60,
  },
  {
    description: "Organic Chicken Bites",
    img_url: "organic_chicken_bites.jpg",
    size: "Small",
    includes: "1 Pack of Chicken Bites",
    category: "Treats/Bones",
    price: 10.49,
    stock: 70,
  },
  {
    description: "Travel Collapsible Bowl Set",
    img_url: "travel_bowl_set.jpg",
    size: "Small",
    includes: "1 Set of 2 Collapsible Bowls",
    category: "Bowls",
    price: 15.99,
    stock: 50,
  },
  {
    description: "Rope Pull Tug Toy",
    img_url: "rope_pull_tug.jpg",
    size: "Medium",
    includes: "1 Tug Toy",
    category: "Toys",
    price: 8.99,
    stock: 65,
  },
  {
    description: "Cooling Dog Bandana",
    img_url: "cooling_bandana.jpg",
    size: "Large",
    includes: "1 Cooling Bandana",
    category: "Grooming",
    price: 13.49,
    stock: 80,
  },
  {
    description: "Dog Training Clicker",
    img_url: "training_clicker.jpg",
    size: "Small",
    includes: "1 Clicker",
    category: "Toys",
    price: 4.99,
    stock: 100,
  },
  {
    description: "Healthy Salmon Treats",
    img_url: "salmon_treats.jpg",
    size: "Medium",
    includes: "1 Bag of Salmon Treats",
    category: "Treats/Bones",
    price: 8.99,
    stock: 90,
  },
  {
    description: "Wooden Elevated Food Bowl",
    img_url: "wooden_bowl.jpg",
    size: "Large",
    includes: "1 Elevated Wooden Bowl Stand",
    category: "Bowls",
    price: 29.99,
    stock: 65,
  },
  {
    description: "Comfortable Orthopedic Bed",
    img_url: "orthopedic_bed.jpg",
    size: "Medium",
    includes: "1 Memory Foam Bed",
    category: "Beds",
    price: 65.99,
    stock: 40,
  },
  {
    description: "Plush Dog Slippers",
    img_url: "plush_slippers.jpg",
    size: "Small",
    includes: "1 Pair of Plush Dog Slippers",
    category: "Grooming",
    price: 19.99,
    stock: 30,
  },
  {
    description: "Deluxe Dog Cot",
    img_url: "deluxe_cot.jpg",
    size: "XLarge",
    includes: "1 Elevated Dog Cot",
    category: "Beds",
    price: 89.99,
    stock: 20,
  },
  {
    description: "Natural Rawhide Chews",
    img_url: "rawhide_chews.jpg",
    size: "Large",
    includes: "1 Bag of Rawhide Chews",
    category: "Treats/Bones",
    price: 15.49,
    stock: 60,
  },
  {
    description: "Squeaky Bone Toy",
    img_url: "squeaky_bone_toy.jpg",
    size: "Medium",
    includes: "1 Squeaky Bone",
    category: "Toys",
    price: 7.99,
    stock: 90,
  },
  {
    description: "Pet Hair Removal Roller",
    img_url: "pet_hair_removal_roller.jpg",
    size: "Small",
    includes: "1 Hair Removal Roller",
    category: "Grooming",
    price: 6.99,
    stock: 110,
  },
  {
    description: "Bamboo Feeding Bowl Set",
    img_url: "bamboo_bowl_set.jpg",
    size: "Large",
    includes: "2 Bamboo Bowls with Stand",
    category: "Bowls",
    price: 35.49,
    stock: 70,
  },
  {
    description: "Interactive Puzzle Toy",
    img_url: "interactive_puzzle_toy.jpg",
    size: "Medium",
    includes: "1 Puzzle Feeding Toy",
    category: "Toys",
    price: 12.99,
    stock: 80,
  },
  {
    description: "Chlorophyll Dog Chews",
    img_url: "chlorophyll_chews.jpg",
    size: "Small",
    includes: "1 Bag of Green Chews",
    category: "Treats/Bones",
    price: 8.49,
    stock: 95,
  },
  {
    description: "Dog GPS Tracker Collar",
    img_url: "gps_tracker_collar.jpg",
    size: "Medium",
    includes: "1 GPS-Enabled Collar",
    category: "Collars, Harnesses & Leashes",
    price: 49.99,
    stock: 55,
  },
  {
    description: "Cooling Water Bottle for Dogs",
    img_url: "cooling_water_bottle.jpg",
    size: "Large",
    includes: "1 Water Bottle with Cooling Feature",
    category: "Bowls",
    price: 18.99,
    stock: 80,
  },
  {
    description: "Fleece Dog Blanket",
    img_url: "fleece_blanket.jpg",
    size: "Medium",
    includes: "1 Cozy Fleece Blanket",
    category: "Beds",
    price: 24.99,
    stock: 75,
  },
  {
    description: "Tough Nylon Leash",
    img_url: "nylon_leash.jpg",
    size: "XLarge",
    includes: "1 Heavy Duty Nylon Leash",
    category: "Collars, Harnesses & Leashes",
    price: 14.99,
    stock: 85,
  },
  {
    description: "Gourmet Dog Biscuit Box",
    img_url: "gourmet_biscuit_box.jpg",
    size: "Small",
    includes: "1 Box of Gourmet Biscuits",
    category: "Treats/Bones",
    price: 13.49,
    stock: 95,
  },
  {
    description: "Bacon & Cheese Chews",
    img_url: "bacon_cheese_chews.jpg",
    size: "Medium",
    includes: "1 Bag of Bacon & Cheese Chews",
    category: "Treats/Bones",
    price: 9.99,
    stock: 60,
  },
  {
    description: "Memory Foam Car Seat Cover",
    img_url: "car_seat_cover_memory_foam.jpg",
    size: "XLarge",
    includes: "1 Foam Car Seat Cover",
    category: "Crates",
    price: 58.99,
    stock: 45,
  },
  {
    description: "Portable Dog Water Dispenser",
    img_url: "portable_water_dispenser.jpg",
    size: "Small",
    includes: "1 Leakproof Water Bottle",
    category: "Bowls",
    price: 11.99,
    stock: 80,
  },
  {
    description: "Chewy Chicken Bites",
    img_url: "chewy_chicken_bites.jpg",
    size: "Large",
    includes: "1 Bag of Chewy Chicken Treats",
    category: "Treats/Bones",
    price: 10.99,
    stock: 65,
  },
  {
    description: "Chew-Proof Dog Bed",
    img_url: "chew_proof_bed.jpg",
    size: "Large",
    includes: "1 Chew-Resistant Bed",
    category: "Beds",
    price: 99.99,
    stock: 30,
  },
  {
    description: "Cooling Gel Pad for Dogs",
    img_url: "cooling_gel_pad.jpg",
    size: "Medium",
    includes: "1 Cooling Gel Pad",
    category: "Beds",
    price: 40.49,
    stock: 50,
  },
  {
    description: "Handmade Leather Dog Collar",
    img_url: "handmade_leather_collar.jpg",
    size: "Small",
    includes: "1 Handmade Leather Collar",
    category: "Collars, Harnesses & Leashes",
    price: 49.99,
    stock: 45,
  },
  {
    description: "Bouncy Tennis Ball Pack",
    img_url: "tennis_ball_pack.jpg",
    size: "Large",
    includes: "1 Pack of 3 Tennis Balls",
    category: "Toys",
    price: 7.49,
    stock: 90,
  },
  {
    description: "Healthy Gravy Dog Toppers",
    img_url: "healthy_gravy_toppers.jpg",
    size: "Medium",
    includes: "1 Bottle of Gravy Toppers",
    category: "Food Toppers",
    price: 9.99,
    stock: 75,
  },
  {
    description: "Furminator Deshedding Tool",
    img_url: "furminator_tool.jpg",
    size: "Small",
    includes: "1 Deshedding Brush",
    category: "Grooming",
    price: 25.99,
    stock: 60,
  },
  {
    description: "Hemp Chews for Relaxation",
    img_url: "hemp_chews_relaxation.jpg",
    size: "Medium",
    includes: "1 Bag of Hemp Chews",
    category: "Treats/Bones",
    price: 12.99,
    stock: 80,
  },
  {
    description: "Fleece Lined Harness",
    img_url: "fleece_harness.jpg",
    size: "Large",
    includes: "1 Soft Fleece Harness",
    category: "Collars, Harnesses & Leashes",
    price: 19.99,
    stock: 85,
  },
  {
    description: "Plastic Bone Chew Toy",
    img_url: "plastic_bone_toy.jpg",
    size: "Medium",
    includes: "1 Bone-Shaped Toy",
    category: "Toys",
    price: 5.99,
    stock: 95,
  },
  {
    description: "Organic Sweet Potato Chews",
    img_url: "sweet_potato_chews.jpg",
    size: "Large",
    includes: "1 Pack of Sweet Potato Chews",
    category: "Treats/Bones",
    price: 8.49,
    stock: 105,
  },
  {
    description: "Quick-Dry Dog Towel",
    img_url: "quick_dry_towel.jpg",
    size: "Medium",
    includes: "1 Quick-Drying Microfiber Towel",
    category: "Grooming",
    price: 12.49,
    stock: 75,
  },
  {
    description: "Waterproof Dog Boots",
    img_url: "waterproof_boots.jpg",
    size: "Large",
    includes: "1 Pair of Waterproof Dog Boots",
    category: "Grooming",
    price: 24.99,
    stock: 60,
  },
  {
    description: "Teething Puppy Chews",
    img_url: "puppy_teething_chews.jpg",
    size: "Small",
    includes: "1 Pack of Puppy Teething Chews",
    category: "Treats/Bones",
    price: 7.99,
    stock: 80,
  },
  {
    description: "Self-Cleaning Slicker Brush",
    img_url: "self_cleaning_brush.jpg",
    size: "Medium",
    includes: "1 Self-Cleaning Slicker Brush",
    category: "Grooming",
    price: 16.49,
    stock: 50,
  },
  {
    description: "Adjustable Nylon Leash",
    img_url: "nylon_leash_adjustable.jpg",
    size: "Medium",
    includes: "1 Adjustable Nylon Leash",
    category: "Collars, Harnesses & Leashes",
    price: 9.99,
    stock: 85,
  },
  {
    description: "Eco-Friendly Dog Poop Bags",
    img_url: "eco_pooper_bags.jpg",
    size: "Small",
    includes: "1 Roll of 100 Bags",
    category: "Grooming",
    price: 5.49,
    stock: 150,
  },
];

export { productsToCreate };
