const productsToCreate = [
  {
    name: "Lamb & Oatmeal Kibble",
    description:
      "Our lamb & oatmeal kibble blends premium lamb and wholesome oatmeal for balanced nutrition.",
    img_url: "lamb_oatmeal_kibble.png",
    size: "Medium",
    includes: "1 Medium bag (12 lb)",
    category: "Food",
    price: 33.94,
    stock: 172,
  },
  {
    name: "Venison & Barley Kibble",
    description:
      "Our venison & barley kibble blends premium venison and wholesome barley for balanced nutrition.",
    img_url: "venison_barley_kibble.png",
    size: "Large",
    includes: "1 Large bag (20 lb)",
    category: "Food",
    price: 37.79,
    stock: 63,
  },
  {
    name: "Salmon & Sweet Potato Kibble",
    description:
      "Our salmon & sweet potato kibble blends premium salmon and wholesome sweet potato for balanced nutrition.",
    img_url: "salmon_sweet_potato_kibble.png",
    size: "Small",
    includes: "1 Small bag (4 lb)",
    category: "Food",
    price: 19.51,
    stock: 173,
  },
  {
    name: "Beef & Quinoa Kibble",
    description:
      "Our beef & quinoa kibble blends premium beef and wholesome quinoa for balanced nutrition.",
    img_url: "beef_quinoa_kibble.png",
    size: "Large",
    includes: "1 Large bag (20 lb)",
    category: "Food",
    price: 38.81,
    stock: 193,
  },
  {
    name: "Turkey & Pea Kibble",
    description:
      "Our turkey & pea kibble blends premium turkey and wholesome pea for balanced nutrition.",
    img_url: "turkey_pea_kibble.png",
    size: "XLarge",
    includes: "1 XLarge bag (30 lb)",
    category: "Food",
    price: 62.54,
    stock: 76,
  },
  {
    name: "Duck & Pumpkin Kibble",
    description:
      "Our duck & pumpkin kibble blends premium duck and wholesome pumpkin for balanced nutrition.",
    img_url: "duck_pumpkin_kibble.png",
    size: "Small",
    includes: "1 Small bag (4 lb)",
    category: "Food",
    price: 16.28,
    stock: 83,
  },
  {
    name: "Rabbit & Cranberry Kibble",
    description:
      "Our rabbit & cranberry kibble blends premium rabbit and wholesome cranberry for balanced nutrition.",
    img_url: "rabbit_cranberry_kibble.png",
    size: "XLarge",
    includes: "1 XLarge bag (30 lb)",
    category: "Food",
    price: 61.65,
    stock: 51,
  },
  {
    name: "Chicken & Brown Rice Kibble",
    description:
      "Our chicken & brown rice kibble blends premium chicken and wholesome brown rice for balanced nutrition.",
    img_url: "chicken_brown_rice_kibble.png",
    size: "Medium",
    includes: "1 Medium bag (12 lb)",
    category: "Food",
    price: 21.91,
    stock: 135,
  },
  {
    name: "Beef Bone Chew",
    description:
      "Our irresistible beef bone chew are crafted from top-quality ingredients for a tasty reward.",
    img_url: "beef_bone_chew.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 7.66,
    stock: 169,
  },
  {
    name: "Chicken Jerky Strips",
    description:
      "Our irresistible chicken jerky strips are crafted from top-quality ingredients for a tasty reward.",
    img_url: "chicken_jerky_strips.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 14.09,
    stock: 25,
  },
  {
    name: "Peanut Butter Biscuits",
    description:
      "Our irresistible peanut butter biscuits are crafted from top-quality ingredients for a tasty reward.",
    img_url: "peanut_butter_biscuits.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 15.8,
    stock: 186,
  },
  {
    name: "Salmon Skin Rolls",
    description:
      "Our irresistible salmon skin rolls are crafted from top-quality ingredients for a tasty reward.",
    img_url: "salmon_skin_rolls.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 20.48,
    stock: 57,
  },
  {
    name: "Dental Sticks",
    description:
      "Our irresistible dental sticks are crafted from top-quality ingredients for a tasty reward.",
    img_url: "dental_sticks.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 7.34,
    stock: 58,
  },
  {
    name: "Yogurt Drops",
    description:
      "Our irresistible yogurt drops are crafted from top-quality ingredients for a tasty reward.",
    img_url: "yogurt_drops.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 12.02,
    stock: 181,
  },
  {
    name: "Duck Tenders",
    description:
      "Our irresistible duck tenders are crafted from top-quality ingredients for a tasty reward.",
    img_url: "duck_tenders.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 18.33,
    stock: 105,
  },
  {
    name: "Lamb Lung Cubes",
    description:
      "Our irresistible lamb lung cubes are crafted from top-quality ingredients for a tasty reward.",
    img_url: "lamb_lung_cubes.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 22.95,
    stock: 143,
  },
  {
    name: "Venison Bites",
    description:
      "Our irresistible venison bites are crafted from top-quality ingredients for a tasty reward.",
    img_url: "venison_bites.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 8.76,
    stock: 127,
  },
  {
    name: "Sweet Potato Chews",
    description:
      "Our irresistible sweet potato chews are crafted from top-quality ingredients for a tasty reward.",
    img_url: "sweet_potato_chews.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 11.08,
    stock: 4,
  },
  {
    name: "Rabbit Ears",
    description:
      "Our irresistible rabbit ears are crafted from top-quality ingredients for a tasty reward.",
    img_url: "rabbit_ears.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 16.16,
    stock: 80,
  },
  {
    name: "Pork Puffs",
    description:
      "Our irresistible pork puffs are crafted from top-quality ingredients for a tasty reward.",
    img_url: "pork_puffs.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 21.12,
    stock: 179,
  },
  {
    name: "Turkey Twists",
    description:
      "Our irresistible turkey twists are crafted from top-quality ingredients for a tasty reward.",
    img_url: "turkey_twists.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 8.69,
    stock: 154,
  },
  {
    name: "Cheese Bites",
    description:
      "Our irresistible cheese bites are crafted from top-quality ingredients for a tasty reward.",
    img_url: "cheese_bites.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 10.51,
    stock: 121,
  },
  {
    name: "Bacon Sausages",
    description:
      "Our irresistible bacon sausages are crafted from top-quality ingredients for a tasty reward.",
    img_url: "bacon_sausages.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 18.1,
    stock: 149,
  },
  {
    name: "Fish Crunchies",
    description:
      "Our irresistible fish crunchies are crafted from top-quality ingredients for a tasty reward.",
    img_url: "fish_crunchies.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 20.7,
    stock: 76,
  },
  {
    name: "Chicken Liver Treats",
    description:
      "Our irresistible chicken liver treats are crafted from top-quality ingredients for a tasty reward.",
    img_url: "chicken_liver_treats.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 5.46,
    stock: 72,
  },
  {
    name: "Beef Tendon Chews",
    description:
      "Our irresistible beef tendon chews are crafted from top-quality ingredients for a tasty reward.",
    img_url: "beef_tendon_chews.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 14.9,
    stock: 141,
  },
  {
    name: "Peanut Butter Cookies",
    description:
      "Our irresistible peanut butter cookies are crafted from top-quality ingredients for a tasty reward.",
    img_url: "peanut_butter_cookies.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 16.0,
    stock: 70,
  },
  {
    name: "Apple Cinnamon Bites",
    description:
      "Our irresistible apple cinnamon bites are crafted from top-quality ingredients for a tasty reward.",
    img_url: "apple_cinnamon_bites.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 22.73,
    stock: 6,
  },
  {
    name: "Coconut Bites",
    description:
      "Our irresistible coconut bites are crafted from top-quality ingredients for a tasty reward.",
    img_url: "coconut_bites.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 7.02,
    stock: 97,
  },
  {
    name: "Pumpkin Biscuits",
    description:
      "Our irresistible pumpkin biscuits are crafted from top-quality ingredients for a tasty reward.",
    img_url: "pumpkin_biscuits.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 14.8,
    stock: 154,
  },
  {
    name: "Blueberry Drops",
    description:
      "Our irresistible blueberry drops are crafted from top-quality ingredients for a tasty reward.",
    img_url: "blueberry_drops.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 16.15,
    stock: 153,
  },
  {
    name: "Banana Chips",
    description:
      "Our irresistible banana chips are crafted from top-quality ingredients for a tasty reward.",
    img_url: "banana_chips.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 22.71,
    stock: 22,
  },
  {
    name: "Carrot Sticks",
    description:
      "Our irresistible carrot sticks are crafted from top-quality ingredients for a tasty reward.",
    img_url: "carrot_sticks.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 7.06,
    stock: 112,
  },
  {
    name: "Coconut Chews",
    description:
      "Our irresistible coconut chews are crafted from top-quality ingredients for a tasty reward.",
    img_url: "coconut_chews.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 13.85,
    stock: 88,
  },
  {
    name: "Salmon Treat Bites",
    description:
      "Our irresistible salmon treat bites are crafted from top-quality ingredients for a tasty reward.",
    img_url: "salmon_treat_bites.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 17.15,
    stock: 75,
  },
  {
    name: "Turkey Jerky Bites",
    description:
      "Our irresistible turkey jerky bites are crafted from top-quality ingredients for a tasty reward.",
    img_url: "turkey_jerky_bites.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 21.0,
    stock: 173,
  },
  {
    name: "Duck Liver Drops",
    description:
      "Our irresistible duck liver drops are crafted from top-quality ingredients for a tasty reward.",
    img_url: "duck_liver_drops.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 8.34,
    stock: 159,
  },
  {
    name: "Lamb Trachea Chews",
    description:
      "Our irresistible lamb trachea chews are crafted from top-quality ingredients for a tasty reward.",
    img_url: "lamb_trachea_chews.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 14.84,
    stock: 3,
  },
  {
    name: "Rabbit Heart Treats",
    description:
      "Our irresistible rabbit heart treats are crafted from top-quality ingredients for a tasty reward.",
    img_url: "rabbit_heart_treats.png",
    size: "Large",
    includes: "1 Large pack (60 treats)",
    category: "Treats",
    price: 18.15,
    stock: 179,
  },
  {
    name: "Beef Liver Bites",
    description:
      "Our irresistible beef liver bites are crafted from top-quality ingredients for a tasty reward.",
    img_url: "beef_liver_bites.png",
    size: "XLarge",
    includes: "1 XLarge pack (100 treats)",
    category: "Treats",
    price: 21.5,
    stock: 88,
  },
  {
    name: "Venison Jerky Strips",
    description:
      "Our irresistible venison jerky strips are crafted from top-quality ingredients for a tasty reward.",
    img_url: "venison_jerky_strips.png",
    size: "Small",
    includes: "1 Small pack (10 treats)",
    category: "Treats",
    price: 9.93,
    stock: 112,
  },
  {
    name: "Sweet Potato Crisps",
    description:
      "Our irresistible sweet potato crisps are crafted from top-quality ingredients for a tasty reward.",
    img_url: "sweet_potato_crisps.png",
    size: "Medium",
    includes: "1 Medium pack (30 treats)",
    category: "Treats",
    price: 14.34,
    stock: 82,
  },
  {
    name: "Tug Rope",
    description: "Our engaging tug rope provides hours of fun and enrichment.",
    img_url: "tug_rope.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 17.81,
    stock: 60,
  },
  {
    name: "Plush Bone",
    description:
      "Our engaging plush bone provides hours of fun and enrichment.",
    img_url: "plush_bone.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 19.56,
    stock: 164,
  },
  {
    name: "Rubber Chew Toy",
    description:
      "Our engaging rubber chew toy provides hours of fun and enrichment.",
    img_url: "rubber_chew_toy.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 28.58,
    stock: 172,
  },
  {
    name: "Interactive Treat Maze",
    description:
      "Our engaging interactive treat maze provides hours of fun and enrichment.",
    img_url: "interactive_treat_maze.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 8.83,
    stock: 77,
  },
  {
    name: "Frisbee",
    description: "Our engaging frisbee provides hours of fun and enrichment.",
    img_url: "frisbee.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 13.1,
    stock: 186,
  },
  {
    name: "Plush Donut",
    description:
      "Our engaging plush donut provides hours of fun and enrichment.",
    img_url: "plush_donut.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 18.3,
    stock: 72,
  },
  {
    name: "Bounce Ball",
    description:
      "Our engaging bounce ball provides hours of fun and enrichment.",
    img_url: "bounce_ball.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 28.12,
    stock: 194,
  },
  {
    name: "Squeaky Duck",
    description:
      "Our engaging squeaky duck provides hours of fun and enrichment.",
    img_url: "squeaky_duck.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 9.09,
    stock: 159,
  },
  {
    name: "Chew Ring",
    description: "Our engaging chew ring provides hours of fun and enrichment.",
    img_url: "chew_ring.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 14.31,
    stock: 8,
  },
  {
    name: "Interactive Puzzle Cube",
    description:
      "Our engaging interactive puzzle cube provides hours of fun and enrichment.",
    img_url: "interactive_puzzle_cube.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 24.41,
    stock: 75,
  },
  {
    name: "Plush Hedgehog",
    description:
      "Our engaging plush hedgehog provides hours of fun and enrichment.",
    img_url: "plush_hedgehog.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 26.23,
    stock: 53,
  },
  {
    name: "Rope Ball",
    description: "Our engaging rope ball provides hours of fun and enrichment.",
    img_url: "rope_ball.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 7.25,
    stock: 118,
  },
  {
    name: "Squeaky Star",
    description:
      "Our engaging squeaky star provides hours of fun and enrichment.",
    img_url: "squeaky_star.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 17.52,
    stock: 21,
  },
  {
    name: "Maze Cube",
    description: "Our engaging maze cube provides hours of fun and enrichment.",
    img_url: "maze_cube.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 24.98,
    stock: 113,
  },
  {
    name: "Plush Squirrel",
    description:
      "Our engaging plush squirrel provides hours of fun and enrichment.",
    img_url: "plush_squirrel.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 28.88,
    stock: 31,
  },
  {
    name: "Tug Torus",
    description: "Our engaging tug torus provides hours of fun and enrichment.",
    img_url: "tug_torus.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 9.42,
    stock: 32,
  },
  {
    name: "Chew Stick",
    description:
      "Our engaging chew stick provides hours of fun and enrichment.",
    img_url: "chew_stick.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 15.03,
    stock: 69,
  },
  {
    name: "Treat Cube",
    description:
      "Our engaging treat cube provides hours of fun and enrichment.",
    img_url: "treat_cube.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 22.28,
    stock: 142,
  },
  {
    name: "Squeezy Turtle",
    description:
      "Our engaging squeezy turtle provides hours of fun and enrichment.",
    img_url: "squeezy_turtle.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 28.46,
    stock: 1,
  },
  {
    name: "Interactive Flipper",
    description:
      "Our engaging interactive flipper provides hours of fun and enrichment.",
    img_url: "interactive_flipper.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 7.18,
    stock: 181,
  },
  {
    name: "Plush Hamburger",
    description:
      "Our engaging plush hamburger provides hours of fun and enrichment.",
    img_url: "plush_hamburger.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 14.51,
    stock: 73,
  },
  {
    name: "Rubber Frisbee",
    description:
      "Our engaging rubber frisbee provides hours of fun and enrichment.",
    img_url: "rubber_frisbee.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 20.03,
    stock: 108,
  },
  {
    name: "Tug Stick",
    description: "Our engaging tug stick provides hours of fun and enrichment.",
    img_url: "tug_stick.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 28.6,
    stock: 61,
  },
  {
    name: "Chew Bar",
    description: "Our engaging chew bar provides hours of fun and enrichment.",
    img_url: "chew_bar.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 10.5,
    stock: 128,
  },
  {
    name: "Tennis Ball Pack",
    description:
      "Our engaging tennis ball pack provides hours of fun and enrichment.",
    img_url: "tennis_ball_pack.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 14.67,
    stock: 154,
  },
  {
    name: "Knotted Rope Duo",
    description:
      "Our engaging knotted rope duo provides hours of fun and enrichment.",
    img_url: "knotted_rope_duo.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 23.54,
    stock: 136,
  },
  {
    name: "Treat-Dispensing Ball",
    description:
      "Our engaging treat-dispensing ball provides hours of fun and enrichment.",
    img_url: "treat_dispensing_ball.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 25.18,
    stock: 27,
  },
  {
    name: "Rubber Bone",
    description:
      "Our engaging rubber bone provides hours of fun and enrichment.",
    img_url: "rubber_bone.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 10.27,
    stock: 150,
  },
  {
    name: "Plush Donut Large",
    description:
      "Our engaging plush donut large provides hours of fun and enrichment.",
    img_url: "plush_donut_large.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 13.21,
    stock: 2,
  },
  {
    name: "Flying Disc",
    description:
      "Our engaging flying disc provides hours of fun and enrichment.",
    img_url: "flying_disc.png",
    size: "Large",
    includes: "1 Large 1 large toy",
    category: "Toys",
    price: 22.01,
    stock: 132,
  },
  {
    name: "Water Toy",
    description: "Our engaging water toy provides hours of fun and enrichment.",
    img_url: "water_toy.png",
    size: "XLarge",
    includes: "1 XLarge 1 jumbo toy",
    category: "Toys",
    price: 26.59,
    stock: 86,
  },
  {
    name: "Glow Wand",
    description: "Our engaging glow wand provides hours of fun and enrichment.",
    img_url: "glow_wand.png",
    size: "Small",
    includes: "1 Small 1 toy",
    category: "Toys",
    price: 7.15,
    stock: 26,
  },
  {
    name: "Squeaky Ball",
    description:
      "Our engaging squeaky ball provides hours of fun and enrichment.",
    img_url: "squeaky_ball.png",
    size: "Medium",
    includes: "1 Medium 1 interactive toy",
    category: "Toys",
    price: 16.33,
    stock: 137,
  },
  {
    name: "Chicken & Beef Gravy",
    description:
      "Our flavorful chicken & beef gravy enhances any meal for picky eaters.",
    img_url: "chicken_beef_gravy.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 11.62,
    stock: 82,
  },
  {
    name: "Salmon & Veggie Mix",
    description:
      "Our flavorful salmon & veggie mix enhances any meal for picky eaters.",
    img_url: "salmon_veggie_mix.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 12.46,
    stock: 153,
  },
  {
    name: "Yogurt Drizzle",
    description:
      "Our flavorful yogurt drizzle enhances any meal for picky eaters.",
    img_url: "yogurt_drizzle.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 17.01,
    stock: 91,
  },
  {
    name: "Pumpkin Pur\u00e9e",
    description:
      "Our flavorful pumpkin pur\u00e9e enhances any meal for picky eaters.",
    img_url: "pumpkin_pur\u00e9e.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 23.5,
    stock: 89,
  },
  {
    name: "Peanut Butter Spread",
    description:
      "Our flavorful peanut butter spread enhances any meal for picky eaters.",
    img_url: "peanut_butter_spread.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 10.64,
    stock: 48,
  },
  {
    name: "Turkey & Cranberry Sauce",
    description:
      "Our flavorful turkey & cranberry sauce enhances any meal for picky eaters.",
    img_url: "turkey_cranberry_sauce.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 13.14,
    stock: 150,
  },
  {
    name: "Beef & Liver Drippings",
    description:
      "Our flavorful beef & liver drippings enhances any meal for picky eaters.",
    img_url: "beef_liver_drippings.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 17.11,
    stock: 25,
  },
  {
    name: "Duck & Apple Topping",
    description:
      "Our flavorful duck & apple topping enhances any meal for picky eaters.",
    img_url: "duck_apple_topping.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 21.53,
    stock: 179,
  },
  {
    name: "Lamb & Rice Broth",
    description:
      "Our flavorful lamb & rice broth enhances any meal for picky eaters.",
    img_url: "lamb_rice_broth.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 11.13,
    stock: 39,
  },
  {
    name: "Fish & Herb Mix",
    description:
      "Our flavorful fish & herb mix enhances any meal for picky eaters.",
    img_url: "fish_herb_mix.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 13.13,
    stock: 8,
  },
  {
    name: "Chicken & Quinoa Blend",
    description:
      "Our flavorful chicken & quinoa blend enhances any meal for picky eaters.",
    img_url: "chicken_quinoa_blend.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 16.37,
    stock: 120,
  },
  {
    name: "Venison & Berry Sauce",
    description:
      "Our flavorful venison & berry sauce enhances any meal for picky eaters.",
    img_url: "venison_berry_sauce.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 21.17,
    stock: 195,
  },
  {
    name: "Salmon & Spinach",
    description:
      "Our flavorful salmon & spinach enhances any meal for picky eaters.",
    img_url: "salmon_spinach.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 11.98,
    stock: 101,
  },
  {
    name: "Turkey & Pumpkin",
    description:
      "Our flavorful turkey & pumpkin enhances any meal for picky eaters.",
    img_url: "turkey_pumpkin.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 13.22,
    stock: 101,
  },
  {
    name: "Beef & Sweet Potato",
    description:
      "Our flavorful beef & sweet potato enhances any meal for picky eaters.",
    img_url: "beef_sweet_potato.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 19.83,
    stock: 156,
  },
  {
    name: "Duck & Pea",
    description: "Our flavorful duck & pea enhances any meal for picky eaters.",
    img_url: "duck_pea.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 20.76,
    stock: 66,
  },
  {
    name: "Lamb & Lentil",
    description:
      "Our flavorful lamb & lentil enhances any meal for picky eaters.",
    img_url: "lamb_lentil.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 11.09,
    stock: 127,
  },
  {
    name: "Chicken & Barley",
    description:
      "Our flavorful chicken & barley enhances any meal for picky eaters.",
    img_url: "chicken_barley.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 14.84,
    stock: 121,
  },
  {
    name: "Salmon & Oatmeal",
    description:
      "Our flavorful salmon & oatmeal enhances any meal for picky eaters.",
    img_url: "salmon_oatmeal.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 19.98,
    stock: 81,
  },
  {
    name: "Turkey & Rice",
    description:
      "Our flavorful turkey & rice enhances any meal for picky eaters.",
    img_url: "turkey_rice.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 20.59,
    stock: 10,
  },
  {
    name: "Beef & Veggie Mix",
    description:
      "Our flavorful beef & veggie mix enhances any meal for picky eaters.",
    img_url: "beef_veggie_mix.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 10.87,
    stock: 140,
  },
  {
    name: "Duck & Carrot",
    description:
      "Our flavorful duck & carrot enhances any meal for picky eaters.",
    img_url: "duck_carrot.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 13.32,
    stock: 87,
  },
  {
    name: "Lamb & Peach",
    description:
      "Our flavorful lamb & peach enhances any meal for picky eaters.",
    img_url: "lamb_peach.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 17.42,
    stock: 189,
  },
  {
    name: "Fish & Kale",
    description:
      "Our flavorful fish & kale enhances any meal for picky eaters.",
    img_url: "fish_kale.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 21.38,
    stock: 173,
  },
  {
    name: "Chicken & Cranberry",
    description:
      "Our flavorful chicken & cranberry enhances any meal for picky eaters.",
    img_url: "chicken_cranberry.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 11.25,
    stock: 120,
  },
  {
    name: "Venison & Pumpkin",
    description:
      "Our flavorful venison & pumpkin enhances any meal for picky eaters.",
    img_url: "venison_pumpkin.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 12.87,
    stock: 140,
  },
  {
    name: "Salmon & Banana",
    description:
      "Our flavorful salmon & banana enhances any meal for picky eaters.",
    img_url: "salmon_banana.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 18.6,
    stock: 84,
  },
  {
    name: "Turkey & Pea",
    description:
      "Our flavorful turkey & pea enhances any meal for picky eaters.",
    img_url: "turkey_pea.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 22.27,
    stock: 142,
  },
  {
    name: "Beef & Broccoli",
    description:
      "Our flavorful beef & broccoli enhances any meal for picky eaters.",
    img_url: "beef_broccoli.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 11.17,
    stock: 163,
  },
  {
    name: "Duck & Sweet Potato",
    description:
      "Our flavorful duck & sweet potato enhances any meal for picky eaters.",
    img_url: "duck_sweet_potato.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 14.19,
    stock: 8,
  },
  {
    name: "Lamb & Apple",
    description:
      "Our flavorful lamb & apple enhances any meal for picky eaters.",
    img_url: "lamb_apple.png",
    size: "Large",
    includes: "1 Large 16 oz jar",
    category: "Food Toppers",
    price: 18.07,
    stock: 23,
  },
  {
    name: "Fish & Sweet Potato",
    description:
      "Our flavorful fish & sweet potato enhances any meal for picky eaters.",
    img_url: "fish_sweet_potato.png",
    size: "XLarge",
    includes: "1 XLarge 32 oz jar",
    category: "Food Toppers",
    price: 22.5,
    stock: 140,
  },
  {
    name: "Chicken & Spinach",
    description:
      "Our flavorful chicken & spinach enhances any meal for picky eaters.",
    img_url: "chicken_spinach.png",
    size: "Small",
    includes: "1 Small 4 oz jar",
    category: "Food Toppers",
    price: 10.53,
    stock: 199,
  },
  {
    name: "Turkey & Herb",
    description:
      "Our flavorful turkey & herb enhances any meal for picky eaters.",
    img_url: "turkey_herb.png",
    size: "Medium",
    includes: "1 Medium 8 oz jar",
    category: "Food Toppers",
    price: 13.3,
    stock: 29,
  },
  {
    name: "Portable Wire Crate",
    description:
      "Our sturdy portable wire crate offers safety and comfort for travel or home use.",
    img_url: "portable_wire_crate.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 30.16,
    stock: 101,
  },
  {
    name: "Plastic Travel Crate",
    description:
      "Our sturdy plastic travel crate offers safety and comfort for travel or home use.",
    img_url: "plastic_travel_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 52.41,
    stock: 134,
  },
  {
    name: "Soft-Sided Crate",
    description:
      "Our sturdy soft-sided crate offers safety and comfort for travel or home use.",
    img_url: "soft_sided_crate.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 66.06,
    stock: 60,
  },
  {
    name: "Heavy-Duty Metal Crate",
    description:
      "Our sturdy heavy-duty metal crate offers safety and comfort for travel or home use.",
    img_url: "heavy_duty_metal_crate.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 91.92,
    stock: 171,
  },
  {
    name: "Foldable Crate",
    description:
      "Our sturdy foldable crate offers safety and comfort for travel or home use.",
    img_url: "foldable_crate.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 34.42,
    stock: 104,
  },
  {
    name: "Deluxe Padded Crate",
    description:
      "Our sturdy deluxe padded crate offers safety and comfort for travel or home use.",
    img_url: "deluxe_padded_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 56.1,
    stock: 190,
  },
  {
    name: "Ventilated Crate",
    description:
      "Our sturdy ventilated crate offers safety and comfort for travel or home use.",
    img_url: "ventilated_crate.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 71.71,
    stock: 197,
  },
  {
    name: "Aluminum Travel Crate",
    description:
      "Our sturdy aluminum travel crate offers safety and comfort for travel or home use.",
    img_url: "aluminum_travel_crate.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 92.35,
    stock: 126,
  },
  {
    name: "Rust-Resistant Crate",
    description:
      "Our sturdy rust-resistant crate offers safety and comfort for travel or home use.",
    img_url: "rust_resistant_crate.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 32.82,
    stock: 186,
  },
  {
    name: "Double-Door Crate",
    description:
      "Our sturdy double-door crate offers safety and comfort for travel or home use.",
    img_url: "double_door_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 58.86,
    stock: 9,
  },
  {
    name: "Compact Soft Crate",
    description:
      "Our sturdy compact soft crate offers safety and comfort for travel or home use.",
    img_url: "compact_soft_crate.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 72.32,
    stock: 63,
  },
  {
    name: "Outdoor Crate",
    description:
      "Our sturdy outdoor crate offers safety and comfort for travel or home use.",
    img_url: "outdoor_crate.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 81.63,
    stock: 48,
  },
  {
    name: "Decorative Wood Crate",
    description:
      "Our sturdy decorative wood crate offers safety and comfort for travel or home use.",
    img_url: "decorative_wood_crate.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 35.75,
    stock: 36,
  },
  {
    name: "Mesh Crate",
    description:
      "Our sturdy mesh crate offers safety and comfort for travel or home use.",
    img_url: "mesh_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 55.13,
    stock: 56,
  },
  {
    name: "Adjustable Crate",
    description:
      "Our sturdy adjustable crate offers safety and comfort for travel or home use.",
    img_url: "adjustable_crate.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 67.81,
    stock: 30,
  },
  {
    name: "Stackable Crate",
    description:
      "Our sturdy stackable crate offers safety and comfort for travel or home use.",
    img_url: "stackable_crate.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 94.33,
    stock: 123,
  },
  {
    name: "Cooling Crate",
    description:
      "Our sturdy cooling crate offers safety and comfort for travel or home use.",
    img_url: "cooling_crate.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 37.33,
    stock: 60,
  },
  {
    name: "Insulated Crate",
    description:
      "Our sturdy insulated crate offers safety and comfort for travel or home use.",
    img_url: "insulated_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 56.94,
    stock: 91,
  },
  {
    name: "Chew-Proof Crate",
    description:
      "Our sturdy chew-proof crate offers safety and comfort for travel or home use.",
    img_url: "chew_proof_crate.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 74.02,
    stock: 48,
  },
  {
    name: "Collapsible Crate",
    description:
      "Our sturdy collapsible crate offers safety and comfort for travel or home use.",
    img_url: "collapsible_crate.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 86.46,
    stock: 4,
  },
  {
    name: "Crate with Wheels",
    description:
      "Our sturdy crate with wheels offers safety and comfort for travel or home use.",
    img_url: "crate_with_wheels.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 38.22,
    stock: 194,
  },
  {
    name: "Eco-Friendly Crate",
    description:
      "Our sturdy eco-friendly crate offers safety and comfort for travel or home use.",
    img_url: "eco_friendly_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 52.96,
    stock: 186,
  },
  {
    name: "Deluxe Wire Crate",
    description:
      "Our sturdy deluxe wire crate offers safety and comfort for travel or home use.",
    img_url: "deluxe_wire_crate.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 74.3,
    stock: 108,
  },
  {
    name: "Concealable Cover",
    description:
      "Our sturdy concealable cover offers safety and comfort for travel or home use.",
    img_url: "concealable_cover.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 86.47,
    stock: 150,
  },
  {
    name: "Photo Crate",
    description:
      "Our sturdy photo crate offers safety and comfort for travel or home use.",
    img_url: "photo_crate.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 32.33,
    stock: 173,
  },
  {
    name: "Expandable Crate",
    description:
      "Our sturdy expandable crate offers safety and comfort for travel or home use.",
    img_url: "expandable_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 47.58,
    stock: 177,
  },
  {
    name: "Crate with Divider",
    description:
      "Our sturdy crate with divider offers safety and comfort for travel or home use.",
    img_url: "crate_with_divider.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 73.51,
    stock: 164,
  },
  {
    name: "Puppy Starter Crate",
    description:
      "Our sturdy puppy starter crate offers safety and comfort for travel or home use.",
    img_url: "puppy_starter_crate.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 99.25,
    stock: 139,
  },
  {
    name: "XL Travel Crate",
    description:
      "Our sturdy xl travel crate offers safety and comfort for travel or home use.",
    img_url: "xl_travel_crate.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 38.17,
    stock: 175,
  },
  {
    name: "XXL Wire Crate",
    description:
      "Our sturdy xxl wire crate offers safety and comfort for travel or home use.",
    img_url: "xxl_wire_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 49.32,
    stock: 8,
  },
  {
    name: "Steel Frame Crate",
    description:
      "Our sturdy steel frame crate offers safety and comfort for travel or home use.",
    img_url: "steel_frame_crate.png",
    size: "Large",
    includes: "1 Large Fits up to 50 lbs",
    category: "Crates",
    price: 70.53,
    stock: 183,
  },
  {
    name: "Canvas Crate",
    description:
      "Our sturdy canvas crate offers safety and comfort for travel or home use.",
    img_url: "canvas_crate.png",
    size: "XLarge",
    includes: "1 XLarge Fits up to 70 lbs",
    category: "Crates",
    price: 98.9,
    stock: 57,
  },
  {
    name: "Crate with Tray",
    description:
      "Our sturdy crate with tray offers safety and comfort for travel or home use.",
    img_url: "crate_with_tray.png",
    size: "Small",
    includes: "1 Small Fits up to 15 lbs",
    category: "Crates",
    price: 33.29,
    stock: 44,
  },
  {
    name: "Outdoor Mesh Crate",
    description:
      "Our sturdy outdoor mesh crate offers safety and comfort for travel or home use.",
    img_url: "outdoor_mesh_crate.png",
    size: "Medium",
    includes: "1 Medium Fits up to 30 lbs",
    category: "Crates",
    price: 50.78,
    stock: 183,
  },
  {
    name: "Nylon Collar",
    description: "Our durable nylon collar combines style and functionality.",
    img_url: "nylon_collar.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 12.44,
    stock: 97,
  },
  {
    name: "Leather Collar",
    description: "Our durable leather collar combines style and functionality.",
    img_url: "leather_collar.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 21.42,
    stock: 116,
  },
  {
    name: "Reflective Harness",
    description:
      "Our durable reflective harness combines style and functionality.",
    img_url: "reflective_harness.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 29.32,
    stock: 145,
  },
  {
    name: "Padded Harness",
    description: "Our durable padded harness combines style and functionality.",
    img_url: "padded_harness.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 40.24,
    stock: 74,
  },
  {
    name: "Retractable Leash",
    description:
      "Our durable retractable leash combines style and functionality.",
    img_url: "retractable_leash.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 12.81,
    stock: 155,
  },
  {
    name: "Rope Leash",
    description: "Our durable rope leash combines style and functionality.",
    img_url: "rope_leash.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 18.48,
    stock: 114,
  },
  {
    name: "Chain Leash",
    description: "Our durable chain leash combines style and functionality.",
    img_url: "chain_leash.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 28.4,
    stock: 173,
  },
  {
    name: "Hands-Free Leash",
    description:
      "Our durable hands-free leash combines style and functionality.",
    img_url: "hands_free_leash.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 40.57,
    stock: 153,
  },
  {
    name: "Martingale Collar",
    description:
      "Our durable martingale collar combines style and functionality.",
    img_url: "martingale_collar.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 14.6,
    stock: 148,
  },
  {
    name: "Breakaway Collar",
    description:
      "Our durable breakaway collar combines style and functionality.",
    img_url: "breakaway_collar.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 15.76,
    stock: 2,
  },
  {
    name: "Step-In Harness",
    description:
      "Our durable step-in harness combines style and functionality.",
    img_url: "step_in_harness.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 30.9,
    stock: 53,
  },
  {
    name: "No-Pull Harness",
    description:
      "Our durable no-pull harness combines style and functionality.",
    img_url: "no_pull_harness.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 43.42,
    stock: 44,
  },
  {
    name: "Adjustable Leash",
    description:
      "Our durable adjustable leash combines style and functionality.",
    img_url: "adjustable_leash.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 14.86,
    stock: 164,
  },
  {
    name: "Bungee Leash",
    description: "Our durable bungee leash combines style and functionality.",
    img_url: "bungee_leash.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 24.85,
    stock: 187,
  },
  {
    name: "Floral Collar",
    description: "Our durable floral collar combines style and functionality.",
    img_url: "floral_collar.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 26.65,
    stock: 144,
  },
  {
    name: "Studded Collar",
    description: "Our durable studded collar combines style and functionality.",
    img_url: "studded_collar.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 35.85,
    stock: 102,
  },
  {
    name: "Personalized Collar",
    description:
      "Our durable personalized collar combines style and functionality.",
    img_url: "personalized_collar.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 10.13,
    stock: 98,
  },
  {
    name: "Glow-in-the-Dark Leash",
    description:
      "Our durable glow-in-the-dark leash combines style and functionality.",
    img_url: "glow_in_the_dark_leash.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 21.87,
    stock: 127,
  },
  {
    name: "Traffic Handle Leash",
    description:
      "Our durable traffic handle leash combines style and functionality.",
    img_url: "traffic_handle_leash.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 28.48,
    stock: 163,
  },
  {
    name: "Double Clip Leash",
    description:
      "Our durable double clip leash combines style and functionality.",
    img_url: "double_clip_leash.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 44.8,
    stock: 5,
  },
  {
    name: "Seatbelt Tether",
    description:
      "Our durable seatbelt tether combines style and functionality.",
    img_url: "seatbelt_tether.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 12.12,
    stock: 77,
  },
  {
    name: "Safety Harness",
    description: "Our durable safety harness combines style and functionality.",
    img_url: "safety_harness.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 23.89,
    stock: 46,
  },
  {
    name: "Vest Harness",
    description: "Our durable vest harness combines style and functionality.",
    img_url: "vest_harness.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 32.6,
    stock: 165,
  },
  {
    name: "Front-Clip Harness",
    description:
      "Our durable front-clip harness combines style and functionality.",
    img_url: "front_clip_harness.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 35.85,
    stock: 169,
  },
  {
    name: "Back-Clip Harness",
    description:
      "Our durable back-clip harness combines style and functionality.",
    img_url: "back_clip_harness.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 11.79,
    stock: 179,
  },
  {
    name: "Padded Leash",
    description: "Our durable padded leash combines style and functionality.",
    img_url: "padded_leash.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 17.94,
    stock: 189,
  },
  {
    name: "Elastic Leash",
    description: "Our durable elastic leash combines style and functionality.",
    img_url: "elastic_leash.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 34.61,
    stock: 185,
  },
  {
    name: "Harness with Handle",
    description:
      "Our durable harness with handle combines style and functionality.",
    img_url: "harness_with_handle.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 38.35,
    stock: 20,
  },
  {
    name: "Leash with Traffic Handle",
    description:
      "Our durable leash with traffic handle combines style and functionality.",
    img_url: "leash_with_traffic_handle.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 10.54,
    stock: 59,
  },
  {
    name: "Reflective Collar",
    description:
      "Our durable reflective collar combines style and functionality.",
    img_url: "reflective_collar.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 15.12,
    stock: 7,
  },
  {
    name: "Waterproof Leash",
    description:
      "Our durable waterproof leash combines style and functionality.",
    img_url: "waterproof_leash.png",
    size: "Large",
    includes: "1 Large Fits neck 18-24 inches",
    category: "Collars, Harnesses & Leashes",
    price: 30.9,
    stock: 178,
  },
  {
    name: "Braided Collar",
    description: "Our durable braided collar combines style and functionality.",
    img_url: "braided_collar.png",
    size: "XLarge",
    includes: "1 XLarge Fits neck 24-30 inches",
    category: "Collars, Harnesses & Leashes",
    price: 38.99,
    stock: 112,
  },
  {
    name: "Chain Choke Collar",
    description:
      "Our durable chain choke collar combines style and functionality.",
    img_url: "chain_choke_collar.png",
    size: "Small",
    includes: "1 Small Fits neck 8-12 inches",
    category: "Collars, Harnesses & Leashes",
    price: 12.3,
    stock: 174,
  },
  {
    name: "Choke-Free Collar",
    description:
      "Our durable choke-free collar combines style and functionality.",
    img_url: "choke_free_collar.png",
    size: "Medium",
    includes: "1 Medium Fits neck 12-18 inches",
    category: "Collars, Harnesses & Leashes",
    price: 23.2,
    stock: 50,
  },
  {
    name: "Bolster Bed",
    description: "Our cozy bolster bed ensures restful sleep and support.",
    img_url: "bolster_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 42.45,
    stock: 135,
  },
  {
    name: "Donut Bed",
    description: "Our cozy donut bed ensures restful sleep and support.",
    img_url: "donut_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 51.28,
    stock: 97,
  },
  {
    name: "Cooling Gel Bed",
    description: "Our cozy cooling gel bed ensures restful sleep and support.",
    img_url: "cooling_gel_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 77.39,
    stock: 175,
  },
  {
    name: "Elevated Mesh Bed",
    description:
      "Our cozy elevated mesh bed ensures restful sleep and support.",
    img_url: "elevated_mesh_bed.png",
    size: "Small",
    includes: "1 Small 24 x 18 inches",
    category: "Beds",
    price: 25.09,
    stock: 52,
  },
  {
    name: "Heated Bed",
    description: "Our cozy heated bed ensures restful sleep and support.",
    img_url: "heated_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 31.92,
    stock: 49,
  },
  {
    name: "Waterproof Bed",
    description: "Our cozy waterproof bed ensures restful sleep and support.",
    img_url: "waterproof_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 56.87,
    stock: 53,
  },
  {
    name: "Nest-Style Bed",
    description: "Our cozy nest-style bed ensures restful sleep and support.",
    img_url: "nest_style_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 71.2,
    stock: 188,
  },
  {
    name: "Travel Bed",
    description: "Our cozy travel bed ensures restful sleep and support.",
    img_url: "travel_bed.png",
    size: "Small",
    includes: "1 Small 24 x 18 inches",
    category: "Beds",
    price: 29.62,
    stock: 34,
  },
  {
    name: "Reversible Bed",
    description: "Our cozy reversible bed ensures restful sleep and support.",
    img_url: "reversible_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 31.07,
    stock: 2,
  },
  {
    name: "Orthopedic Pillow Bed",
    description:
      "Our cozy orthopedic pillow bed ensures restful sleep and support.",
    img_url: "orthopedic_pillow_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 59.02,
    stock: 54,
  },
  {
    name: "Luxury Faux Fur Bed",
    description:
      "Our cozy luxury faux fur bed ensures restful sleep and support.",
    img_url: "luxury_faux_fur_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 72.73,
    stock: 54,
  },
  {
    name: "Canvas Roll-Up Bed",
    description:
      "Our cozy canvas roll-up bed ensures restful sleep and support.",
    img_url: "canvas_roll_up_bed.png",
    size: "Small",
    includes: "1 Small 24 x 18 inches",
    category: "Beds",
    price: 20.17,
    stock: 66,
  },
  {
    name: "Cave-Style Bed",
    description: "Our cozy cave-style bed ensures restful sleep and support.",
    img_url: "cave_style_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 39.74,
    stock: 67,
  },
  {
    name: "Velvet Comfort Bed",
    description:
      "Our cozy velvet comfort bed ensures restful sleep and support.",
    img_url: "velvet_comfort_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 46.78,
    stock: 82,
  },
  {
    name: "Canvas Raised Bed",
    description:
      "Our cozy canvas raised bed ensures restful sleep and support.",
    img_url: "canvas_raised_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 67.66,
    stock: 70,
  },
  {
    name: "Round Pillow Bed",
    description: "Our cozy round pillow bed ensures restful sleep and support.",
    img_url: "round_pillow_bed.png",
    size: "Small",
    includes: "1 Small 24 x 18 inches",
    category: "Beds",
    price: 20.34,
    stock: 69,
  },
  {
    name: "Travel Pad Bed",
    description: "Our cozy travel pad bed ensures restful sleep and support.",
    img_url: "travel_pad_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 33.63,
    stock: 189,
  },
  {
    name: "Indoor/Outdoor Bed",
    description:
      "Our cozy indoor/outdoor bed ensures restful sleep and support.",
    img_url: "indoor/outdoor_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 48.8,
    stock: 37,
  },
  {
    name: "Deluxe Pillow Bed",
    description:
      "Our cozy deluxe pillow bed ensures restful sleep and support.",
    img_url: "deluxe_pillow_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 72.86,
    stock: 7,
  },
  {
    name: "Supportive Pillow Bed",
    description:
      "Our cozy supportive pillow bed ensures restful sleep and support.",
    img_url: "supportive_pillow_bed.png",
    size: "Small",
    includes: "1 Small 24 x 18 inches",
    category: "Beds",
    price: 27.12,
    stock: 113,
  },
  {
    name: "Chevron Bed",
    description: "Our cozy chevron bed ensures restful sleep and support.",
    img_url: "chevron_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 42.26,
    stock: 55,
  },
  {
    name: "Striped Bed",
    description: "Our cozy striped bed ensures restful sleep and support.",
    img_url: "striped_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 58.96,
    stock: 119,
  },
  {
    name: "Plaid Bed",
    description: "Our cozy plaid bed ensures restful sleep and support.",
    img_url: "plaid_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 69.9,
    stock: 188,
  },
  {
    name: "Patchwork Bed",
    description: "Our cozy patchwork bed ensures restful sleep and support.",
    img_url: "patchwork_bed.png",
    size: "Small",
    includes: "1 Small 24 x 18 inches",
    category: "Beds",
    price: 22.11,
    stock: 83,
  },
  {
    name: "Sailor Stripe Bed",
    description:
      "Our cozy sailor stripe bed ensures restful sleep and support.",
    img_url: "sailor_stripe_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 40.52,
    stock: 115,
  },
  {
    name: "Floral Bed",
    description: "Our cozy floral bed ensures restful sleep and support.",
    img_url: "floral_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 55.9,
    stock: 200,
  },
  {
    name: "Boho Chic Bed",
    description: "Our cozy boho chic bed ensures restful sleep and support.",
    img_url: "boho_chic_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 73.9,
    stock: 132,
  },
  {
    name: "Patchwork Canvas Bed",
    description:
      "Our cozy patchwork canvas bed ensures restful sleep and support.",
    img_url: "patchwork_canvas_bed.png",
    size: "Small",
    includes: "1 Small 24 x 18 inches",
    category: "Beds",
    price: 22.31,
    stock: 33,
  },
  {
    name: "Outdoor Lounger Bed",
    description:
      "Our cozy outdoor lounger bed ensures restful sleep and support.",
    img_url: "outdoor_lounger_bed.png",
    size: "Medium",
    includes: "1 Medium 30 x 20 inches",
    category: "Beds",
    price: 30.54,
    stock: 3,
  },
  {
    name: "Indoor Lounger Bed",
    description:
      "Our cozy indoor lounger bed ensures restful sleep and support.",
    img_url: "indoor_lounger_bed.png",
    size: "Large",
    includes: "1 Large 36 x 24 inches",
    category: "Beds",
    price: 50.45,
    stock: 33,
  },
  {
    name: "Orthopedic Memory Foam Bed",
    description:
      "Our cozy orthopedic memory foam bed ensures restful sleep and support.",
    img_url: "orthopedic_memory_foam_bed.png",
    size: "XLarge",
    includes: "1 XLarge 48 x 30 inches",
    category: "Beds",
    price: 60.7,
    stock: 90,
  },
  {
    name: "Stainless Steel Bowl",
    description:
      "Our versatile stainless steel bowl is perfect for meals and water.",
    img_url: "stainless_steel_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 6.78,
    stock: 40,
  },
  {
    name: "Ceramic Bowl",
    description: "Our versatile ceramic bowl is perfect for meals and water.",
    img_url: "ceramic_bowl.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 11.72,
    stock: 181,
  },
  {
    name: "Silicone Foldable Bowl",
    description:
      "Our versatile silicone foldable bowl is perfect for meals and water.",
    img_url: "silicone_foldable_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 19.34,
    stock: 199,
  },
  {
    name: "Elevated Bowl",
    description: "Our versatile elevated bowl is perfect for meals and water.",
    img_url: "elevated_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 23.93,
    stock: 182,
  },
  {
    name: "Non-Slip Bowl",
    description: "Our versatile non-slip bowl is perfect for meals and water.",
    img_url: "non_slip_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 5.92,
    stock: 40,
  },
  {
    name: "Double Bowl Set",
    description:
      "Our versatile double bowl set is perfect for meals and water.",
    img_url: "double_bowl_set.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 12.97,
    stock: 175,
  },
  {
    name: "Travel Water Bottle Bowl",
    description:
      "Our versatile travel water bottle bowl is perfect for meals and water.",
    img_url: "travel_water_bottle_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 17.7,
    stock: 154,
  },
  {
    name: "Slow Feeder Bowl",
    description:
      "Our versatile slow feeder bowl is perfect for meals and water.",
    img_url: "slow_feeder_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 23.89,
    stock: 146,
  },
  {
    name: "Collapsible Bowl",
    description:
      "Our versatile collapsible bowl is perfect for meals and water.",
    img_url: "collapsible_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 9.67,
    stock: 157,
  },
  {
    name: "Divider Bowl",
    description: "Our versatile divider bowl is perfect for meals and water.",
    img_url: "divider_bowl.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 13.66,
    stock: 10,
  },
  {
    name: "Melamine Bowl",
    description: "Our versatile melamine bowl is perfect for meals and water.",
    img_url: "melamine_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 19.66,
    stock: 148,
  },
  {
    name: "Bamboo Bowl",
    description: "Our versatile bamboo bowl is perfect for meals and water.",
    img_url: "bamboo_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 24.98,
    stock: 70,
  },
  {
    name: "Plastic Bowl",
    description: "Our versatile plastic bowl is perfect for meals and water.",
    img_url: "plastic_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 9.59,
    stock: 53,
  },
  {
    name: "Rust-Resistant Bowl",
    description:
      "Our versatile rust-resistant bowl is perfect for meals and water.",
    img_url: "rust_resistant_bowl.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 10.65,
    stock: 68,
  },
  {
    name: "Insulated Bowl",
    description: "Our versatile insulated bowl is perfect for meals and water.",
    img_url: "insulated_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 16.88,
    stock: 38,
  },
  {
    name: "Smart Bowl",
    description: "Our versatile smart bowl is perfect for meals and water.",
    img_url: "smart_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 23.45,
    stock: 29,
  },
  {
    name: "Porcelain Bowl",
    description: "Our versatile porcelain bowl is perfect for meals and water.",
    img_url: "porcelain_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 7.3,
    stock: 156,
  },
  {
    name: "Stackable Bowl",
    description: "Our versatile stackable bowl is perfect for meals and water.",
    img_url: "stackable_bowl.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 13.81,
    stock: 133,
  },
  {
    name: "Color-Change Bowl",
    description:
      "Our versatile color-change bowl is perfect for meals and water.",
    img_url: "color_change_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 15.41,
    stock: 115,
  },
  {
    name: "Personalized Bowl",
    description:
      "Our versatile personalized bowl is perfect for meals and water.",
    img_url: "personalized_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 21.19,
    stock: 1,
  },
  {
    name: "Emoji Bowl",
    description: "Our versatile emoji bowl is perfect for meals and water.",
    img_url: "emoji_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 6.2,
    stock: 66,
  },
  {
    name: "Travel Scoop Bowl",
    description:
      "Our versatile travel scoop bowl is perfect for meals and water.",
    img_url: "travel_scoop_bowl.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 13.91,
    stock: 186,
  },
  {
    name: "Mesh Feeder Bowl",
    description:
      "Our versatile mesh feeder bowl is perfect for meals and water.",
    img_url: "mesh_feeder_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 16.54,
    stock: 121,
  },
  {
    name: "Robot Feeder Bowl",
    description:
      "Our versatile robot feeder bowl is perfect for meals and water.",
    img_url: "robot_feeder_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 24.14,
    stock: 137,
  },
  {
    name: "Gravity Bowl",
    description: "Our versatile gravity bowl is perfect for meals and water.",
    img_url: "gravity_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 5.34,
    stock: 59,
  },
  {
    name: "Lidded Bowl",
    description: "Our versatile lidded bowl is perfect for meals and water.",
    img_url: "lidded_bowl.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 14.88,
    stock: 94,
  },
  {
    name: "Portion Control Bowl",
    description:
      "Our versatile portion control bowl is perfect for meals and water.",
    img_url: "portion_control_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 18.29,
    stock: 181,
  },
  {
    name: "Stoneware Bowl",
    description: "Our versatile stoneware bowl is perfect for meals and water.",
    img_url: "stoneware_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 22.41,
    stock: 81,
  },
  {
    name: "Crystal Bowl",
    description: "Our versatile crystal bowl is perfect for meals and water.",
    img_url: "crystal_bowl.png",
    size: "Small",
    includes: "1 Small 12 oz",
    category: "Bowls",
    price: 8.2,
    stock: 54,
  },
  {
    name: "Dishwasher Safe Bowl",
    description:
      "Our versatile dishwasher safe bowl is perfect for meals and water.",
    img_url: "dishwasher_safe_bowl.png",
    size: "Medium",
    includes: "1 Medium 24 oz",
    category: "Bowls",
    price: 14.52,
    stock: 4,
  },
  {
    name: "Silicone Suction Bowl",
    description:
      "Our versatile silicone suction bowl is perfect for meals and water.",
    img_url: "silicone_suction_bowl.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Bowls",
    price: 19.99,
    stock: 188,
  },
  {
    name: "Ceramic Non-Slip Bowl",
    description:
      "Our versatile ceramic non-slip bowl is perfect for meals and water.",
    img_url: "ceramic_non_slip_bowl.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Bowls",
    price: 23.67,
    stock: 193,
  },
  {
    name: "Gentle Oatmeal Shampoo",
    description:
      "Our professional-grade gentle oatmeal shampoo keeps your dog looking its best.",
    img_url: "gentle_oatmeal_shampoo.png",
    size: "Small",
    includes: "1 Small 8 oz",
    category: "Grooming",
    price: 9.98,
    stock: 66,
  },
  {
    name: "Flea & Tick Shampoo",
    description:
      "Our professional-grade flea & tick shampoo keeps your dog looking its best.",
    img_url: "flea_tick_shampoo.png",
    size: "Medium",
    includes: "1 Medium 16 oz",
    category: "Grooming",
    price: 15.95,
    stock: 146,
  },
  {
    name: "Hypoallergenic Conditioner",
    description:
      "Our professional-grade hypoallergenic conditioner keeps your dog looking its best.",
    img_url: "hypoallergenic_conditioner.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Grooming",
    price: 23.99,
    stock: 82,
  },
  {
    name: "Waterless Shampoo",
    description:
      "Our professional-grade waterless shampoo keeps your dog looking its best.",
    img_url: "waterless_shampoo.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 29.93,
    stock: 120,
  },
  {
    name: "Deshedding Tool",
    description:
      "Our professional-grade deshedding tool keeps your dog looking its best.",
    img_url: "deshedding_tool.png",
    size: "Small",
    includes: "1 Small 8 oz",
    category: "Grooming",
    price: 11.12,
    stock: 119,
  },
  {
    name: "Nail Clippers",
    description:
      "Our professional-grade nail clippers keeps your dog looking its best.",
    img_url: "nail_clippers.png",
    size: "Medium",
    includes: "1 Medium 16 oz",
    category: "Grooming",
    price: 14.33,
    stock: 50,
  },
  {
    name: "Brushing Glove",
    description:
      "Our professional-grade brushing glove keeps your dog looking its best.",
    img_url: "brushing_glove.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Grooming",
    price: 24.46,
    stock: 96,
  },
  {
    name: "Ear Cleaner",
    description:
      "Our professional-grade ear cleaner keeps your dog looking its best.",
    img_url: "ear_cleaner.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 29.54,
    stock: 132,
  },
  {
    name: "Muddy Paws Shampoo",
    description:
      "Our professional-grade muddy paws shampoo keeps your dog looking its best.",
    img_url: "muddy_paws_shampoo.png",
    size: "Small",
    includes: "1 Small 8 oz",
    category: "Grooming",
    price: 10.15,
    stock: 71,
  },
  {
    name: "Teeth Cleaning Gel",
    description:
      "Our professional-grade teeth cleaning gel keeps your dog looking its best.",
    img_url: "teeth_cleaning_gel.png",
    size: "Medium",
    includes: "1 Medium 16 oz",
    category: "Grooming",
    price: 12.85,
    stock: 5,
  },
  {
    name: "Paw Balm",
    description:
      "Our professional-grade paw balm keeps your dog looking its best.",
    img_url: "paw_balm.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Grooming",
    price: 18.68,
    stock: 89,
  },
  {
    name: "Coat Spray",
    description:
      "Our professional-grade coat spray keeps your dog looking its best.",
    img_url: "coat_spray.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 26.76,
    stock: 194,
  },
  {
    name: "Grooming Scissors",
    description:
      "Our professional-grade grooming scissors keeps your dog looking its best.",
    img_url: "grooming_scissors.png",
    size: "Small",
    includes: "1 Small 8 oz",
    category: "Grooming",
    price: 11.93,
    stock: 130,
  },
  {
    name: "Shedding Rake",
    description:
      "Our professional-grade shedding rake keeps your dog looking its best.",
    img_url: "shedding_rake.png",
    size: "Medium",
    includes: "1 Medium 16 oz",
    category: "Grooming",
    price: 15.47,
    stock: 105,
  },
  {
    name: "Shampoo & Conditioner Set",
    description:
      "Our professional-grade shampoo & conditioner set keeps your dog looking its best.",
    img_url: "shampoo_conditioner_set.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Grooming",
    price: 19.73,
    stock: 147,
  },
  {
    name: "Travel Grooming Kit",
    description:
      "Our professional-grade travel grooming kit keeps your dog looking its best.",
    img_url: "travel_grooming_kit.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 29.17,
    stock: 165,
  },
  {
    name: "Brush Set",
    description:
      "Our professional-grade brush set keeps your dog looking its best.",
    img_url: "brush_set.png",
    size: "Small",
    includes: "1 Small 8 oz",
    category: "Grooming",
    price: 8.25,
    stock: 117,
  },
  {
    name: "Dematting Comb",
    description:
      "Our professional-grade dematting comb keeps your dog looking its best.",
    img_url: "dematting_comb.png",
    size: "Medium",
    includes: "1 Medium 16 oz",
    category: "Grooming",
    price: 16.38,
    stock: 78,
  },
  {
    name: "Grooming Apron",
    description:
      "Our professional-grade grooming apron keeps your dog looking its best.",
    img_url: "grooming_apron.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Grooming",
    price: 24.91,
    stock: 65,
  },
  {
    name: "Shampoo Brush",
    description:
      "Our professional-grade shampoo brush keeps your dog looking its best.",
    img_url: "shampoo_brush.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 29.15,
    stock: 7,
  },
  {
    name: "Conditioning Spray",
    description:
      "Our professional-grade conditioning spray keeps your dog looking its best.",
    img_url: "conditioning_spray.png",
    size: "Small",
    includes: "1 Small 8 oz",
    category: "Grooming",
    price: 8.13,
    stock: 145,
  },
  {
    name: "Paw Cleaner",
    description:
      "Our professional-grade paw cleaner keeps your dog looking its best.",
    img_url: "paw_cleaner.png",
    size: "Medium",
    includes: "1 Medium 16 oz",
    category: "Grooming",
    price: 17.86,
    stock: 86,
  },
  {
    name: "Ear Wipes",
    description:
      "Our professional-grade ear wipes keeps your dog looking its best.",
    img_url: "ear_wipes.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Grooming",
    price: 24.18,
    stock: 169,
  },
  {
    name: "Table Mat",
    description:
      "Our professional-grade table mat keeps your dog looking its best.",
    img_url: "table_mat.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 25.1,
    stock: 86,
  },
  {
    name: "Nail File",
    description:
      "Our professional-grade nail file keeps your dog looking its best.",
    img_url: "nail_file.png",
    size: "Small",
    includes: "1 Small 8 oz",
    category: "Grooming",
    price: 8.15,
    stock: 189,
  },
  {
    name: "Paw Salve",
    description:
      "Our professional-grade paw salve keeps your dog looking its best.",
    img_url: "paw_salve.png",
    size: "Medium",
    includes: "1 Medium 16 oz",
    category: "Grooming",
    price: 13.5,
    stock: 124,
  },
  {
    name: "Shedding Blade",
    description:
      "Our professional-grade shedding blade keeps your dog looking its best.",
    img_url: "shedding_blade.png",
    size: "Large",
    includes: "1 Large 32 oz",
    category: "Grooming",
    price: 19.61,
    stock: 172,
  },
  {
    name: "Undercoat Rake",
    description:
      "Our professional-grade undercoat rake keeps your dog looking its best.",
    img_url: "undercoat_rake.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 28.88,
    stock: 116,
  },
  {
    name: "Shampoo Bar",
    description:
      "Our professional-grade shampoo bar keeps your dog looking its best.",
    img_url: "shampoo_bar.png",
    size: "XLarge",
    includes: "1 XLarge 64 oz",
    category: "Grooming",
    price: 25.5,
    stock: 40,
  },
  {
    name: "Bacon Kibble",
    description:
      "Premium Small Bacon Kibble, crafted for the ultimate canine experience in the Food category.",
    img_url: "bacon_kibble.png",
    size: "Small",
    includes: "1 bag",
    category: "Food",
    price: 19.99,
    stock: 50,
  },
  {
    name: "Pumpkin Wet Food",
    description:
      "Premium Medium Pumpkin Wet Food, crafted for the ultimate canine experience in the Food category.",
    img_url: "pumpkin_wet_food.png",
    size: "Medium",
    includes: "1 can",
    category: "Food",
    price: 24.5,
    stock: 30,
  },
  {
    name: "Blueberry Jerky Treat",
    description:
      "Premium Large Blueberry Jerky Treat, crafted for the ultimate canine experience in the Treats/Bones category.",
    img_url: "blueberry_jerky_treat.png",
    size: "Large",
    includes: "1 pack",
    category: "Treats/Bones",
    price: 12.75,
    stock: 75,
  },
  {
    name: "Salmon Dental Bone",
    description:
      "Premium XLarge Salmon Dental Bone, crafted for the ultimate canine experience in the Treats/Bones category.",
    img_url: "salmon_dental_bone.png",
    size: "XLarge",
    includes: "1 bone",
    category: "Treats/Bones",
    price: 15.25,
    stock: 40,
  },
  {
    name: "Turkey Rope Toy",
    description:
      "Premium Small Turkey Rope Toy, crafted for the ultimate canine experience in the Toys category.",
    img_url: "turkey_rope_toy.png",
    size: "Small",
    includes: "1 rope toy",
    category: "Toys",
    price: 18.0,
    stock: 60,
  },
  {
    name: "Lamb Interactive Puzzle",
    description:
      "Premium Medium Lamb Interactive Puzzle, crafted for the ultimate canine experience in the Toys category.",
    img_url: "lamb_interactive_puzzle.png",
    size: "Medium",
    includes: "1 puzzle",
    category: "Toys",
    price: 22.3,
    stock: 25,
  },
  {
    name: "Chicken Plush Toy",
    description:
      "Premium Large Chicken Plush Toy, crafted for the ultimate canine experience in the Toys category.",
    img_url: "chicken_plush_toy.png",
    size: "Large",
    includes: "1 plush toy",
    category: "Toys",
    price: 14.6,
    stock: 80,
  },
  {
    name: "Venison Squeaky Toy",
    description:
      "Premium XLarge Venison Squeaky Toy, crafted for the ultimate canine experience in the Toys category.",
    img_url: "venison_squeaky_toy.png",
    size: "XLarge",
    includes: "1 squeaky toy",
    category: "Toys",
    price: 16.8,
    stock: 45,
  },
  {
    name: "Duck Crate",
    description:
      "Premium Small Duck Crate, crafted for the ultimate canine experience in the Crates category.",
    img_url: "duck_crate.png",
    size: "Small",
    includes: "1 crate",
    category: "Crates",
    price: 45.0,
    stock: 20,
  },
  {
    name: "Kangaroo Dog Bed",
    description:
      "Premium Medium Kangaroo Dog Bed, crafted for the ultimate canine experience in the Beds category.",
    img_url: "kangaroo_dog_bed.png",
    size: "Medium",
    includes: "1 bed",
    category: "Beds",
    price: 39.99,
    stock: 15,
  },
  {
    name: "Peanut Butter Collar",
    description:
      "Premium Large Peanut Butter Collar, crafted for the ultimate canine experience in the Collars, Harnesses & Leashes category.",
    img_url: "peanut_butter_collar.png",
    size: "Large",
    includes: "1 collar",
    category: "Collars, Harnesses & Leashes",
    price: 15.5,
    stock: 70,
  },
  {
    name: "Sweet Potato Harness",
    description:
      "Premium XLarge Sweet Potato Harness, crafted for the ultimate canine experience in the Collars, Harnesses & Leashes category.",
    img_url: "sweet_potato_harness.png",
    size: "XLarge",
    includes: "1 harness",
    category: "Collars, Harnesses & Leashes",
    price: 22.99,
    stock: 55,
  },
  {
    name: "Venison Leash",
    description:
      "Premium Small Venison Leash, crafted for the ultimate canine experience in the Collars, Harnesses & Leashes category.",
    img_url: "venison_leash.png",
    size: "Small",
    includes: "1 leash",
    category: "Collars, Harnesses & Leashes",
    price: 18.75,
    stock: 65,
  },
  {
    name: "Salmon Food Bowl",
    description:
      "Premium Medium Salmon Food Bowl, crafted for the ultimate canine experience in the Bowls category.",
    img_url: "salmon_food_bowl.png",
    size: "Medium",
    includes: "1 bowl",
    category: "Bowls",
    price: 7.99,
    stock: 90,
  },
  {
    name: "Beef Water Bowl",
    description:
      "Premium Large Beef Water Bowl, crafted for the ultimate canine experience in the Bowls category.",
    img_url: "beef_water_bowl.png",
    size: "Large",
    includes: "1 bowl",
    category: "Bowls",
    price: 6.49,
    stock: 100,
  },
  {
    name: "Duck Shampoo",
    description:
      "Premium XLarge Duck Shampoo, crafted for the ultimate canine experience in the Grooming category.",
    img_url: "duck_shampoo.png",
    size: "XLarge",
    includes: "1 bottle",
    category: "Grooming",
    price: 12.0,
    stock: 85,
  },
  {
    name: "Turkey Conditioner",
    description:
      "Premium Small Turkey Conditioner, crafted for the ultimate canine experience in the Grooming category.",
    img_url: "turkey_conditioner.png",
    size: "Small",
    includes: "1 bottle",
    category: "Grooming",
    price: 13.0,
    stock: 80,
  },
  {
    name: "Lamb Brush",
    description:
      "Premium Medium Lamb Brush, crafted for the ultimate canine experience in the Grooming category.",
    img_url: "lamb_brush.png",
    size: "Medium",
    includes: "1 brush",
    category: "Grooming",
    price: 11.5,
    stock: 45,
  },
  {
    name: "Kangaroo Slow Feeder Bowl",
    description:
      "Premium Large Kangaroo Slow Feeder Bowl, crafted for the ultimate canine experience in the Bowls category.",
    img_url: "kangaroo_slow_feeder_bowl.png",
    size: "Large",
    includes: "1 bowl",
    category: "Bowls",
    price: 29.99,
    stock: 35,
  },
  {
    name: "Chicken Food Topper",
    description:
      "Premium XLarge Chicken Food Topper, crafted for the ultimate canine experience in the Food Toppers category.",
    img_url: "chicken_food_topper.png",
    size: "XLarge",
    includes: "1 jar",
    category: "Food Toppers",
    price: 8.99,
    stock: 95,
  },
  {
    name: "Beef & Chicken Jerky Sampler",
    description:
      "Premium Small Beef & Chicken Jerky Sampler, crafted for the ultimate canine experience in the Treats/Bones category.",
    img_url: "beef_chicken_jerky_sampler.png",
    size: "Small",
    includes: "1 sampler pack",
    category: "Treats/Bones",
    price: 19.49,
    stock: 50,
  },
  {
    name: "Salmon & Tuna Wet Food Duo",
    description:
      "Premium Medium Salmon & Tuna Wet Food Duo, crafted for the ultimate canine experience in the Food category.",
    img_url: "salmon_tuna_wet_food_duo.png",
    size: "Medium",
    includes: "2 cans",
    category: "Food",
    price: 23.99,
    stock: 25,
  },
  {
    name: "Pumpkin Spice Kibble",
    description:
      "Premium Large Pumpkin Spice Kibble, crafted for the ultimate canine experience in the Food category.",
    img_url: "pumpkin_spice_kibble.png",
    size: "Large",
    includes: "1 bag",
    category: "Food",
    price: 17.25,
    stock: 60,
  },
  {
    name: "Duck & Sweet Potato Jerky",
    description:
      "Premium XLarge Duck & Sweet Potato Jerky, crafted for the ultimate canine experience in the Treats/Bones category.",
    img_url: "duck_sweet_potato_jerky.png",
    size: "XLarge",
    includes: "1 pack",
    category: "Treats/Bones",
    price: 14.75,
    stock: 30,
  },
  {
    name: "Lamb & Venison Bone Mix",
    description:
      "Premium Small Lamb & Venison Bone Mix, crafted for the ultimate canine experience in the Treats/Bones category.",
    img_url: "lamb_venison_bone_mix.png",
    size: "Small",
    includes: "1 mix pack",
    category: "Treats/Bones",
    price: 16.5,
    stock: 40,
  },
  {
    name: "Kangaroo Hide Chew",
    description:
      "Premium Medium Kangaroo Hide Chew, crafted for the ultimate canine experience in the Treats/Bones category.",
    img_url: "kangaroo_hide_chew.png",
    size: "Medium",
    includes: "1 chew",
    category: "Treats/Bones",
    price: 25.0,
    stock: 20,
  },
  {
    name: "Turkey Feathers Plush Toy",
    description:
      "Premium Large Turkey Feathers Plush Toy, crafted for the ultimate canine experience in the Toys category.",
    img_url: "turkey_feathers_plush_toy.png",
    size: "Large",
    includes: "1 plush toy",
    category: "Toys",
    price: 13.5,
    stock: 50,
  },
  {
    name: "Peanut Butter Dental Stick",
    description:
      "Premium XLarge Peanut Butter Dental Stick, crafted for the ultimate canine experience in the Treats/Bones category.",
    img_url: "peanut_butter_dental_stick.png",
    size: "XLarge",
    includes: "1 stick",
    category: "Treats/Bones",
    price: 10.99,
    stock: 100,
  },
];

export { productsToCreate };
