const usersToCreate = [
  // Admin users
  {
    username: "johndoe",
    password: "password123",
    is_admin: true,
    name: "John Doe",
    email_address: "johndoe@example.com",
    mailing_address: "123 Admin St",
    phone_number: "+1-555-1234",
    billing_address: "123 Admin St",
  },
  {
    username: "janedoe",
    password: "password123",
    is_admin: true,
    name: "Jane Doe",
    email_address: "janedoe@example.com",
    mailing_address: "234 Admin Rd",
    phone_number: "+1-555-2345",
    billing_address: "234 Admin Rd",
  },
  {
    username: "michaelbrown",
    password: "password123",
    is_admin: true,
    name: "Michael Brown",
    email_address: "michaelbrown@example.com",
    mailing_address: "345 Admin Ave",
    phone_number: "+1-555-3456",
    billing_address: "345 Admin Ave",
  },
  {
    username: "emilyclark",
    password: "password123",
    is_admin: true,
    name: "Emily Clark",
    email_address: "emilyclark@example.com",
    mailing_address: "456 Admin Blvd",
    phone_number: "+1-555-4567",
    billing_address: "456 Admin Blvd",
  },
  {
    username: "alexisjohnson",
    password: "password123",
    is_admin: true,
    name: "Alexis Johnson",
    email_address: "alexisjohnson@example.com",
    mailing_address: "567 Admin Ln",
    phone_number: "+1-555-5678",
    billing_address: "567 Admin Ln",
  },

  // Regular users
  {
    username: "kylewilliams",
    password: "letmein1",
    is_admin: false,
    name: "Kyle Williams",
    email_address: "kylewilliams@example.com",
    mailing_address: "101 Maple St",
    phone_number: "+1-555-6789",
    billing_address: "101 Maple St",
  },
  {
    username: "ashleyturner",
    password: "welcome123",
    is_admin: false,
    name: "Ashley Turner",
    email_address: "ashleyturner@example.com",
    mailing_address: "202 Oak Rd",
    phone_number: "+1-555-7890",
    billing_address: "202 Oak Rd",
  },
  {
    username: "chrisdavies",
    password: "chris123",
    is_admin: false,
    name: "Chris Davies",
    email_address: "chrisdavies@example.com",
    mailing_address: "303 Pine Ave",
    phone_number: "+1-555-8901",
    billing_address: "303 Pine Ave",
  },
  {
    username: "sarahmiller",
    password: "sarah123",
    is_admin: false,
    name: "Sarah Miller",
    email_address: "sarahmiller@example.com",
    mailing_address: "404 Birch Blvd",
    phone_number: "+1-555-9012",
    billing_address: "404 Birch Blvd",
  },
  {
    username: "danielgomez",
    password: "daniel123",
    is_admin: false,
    name: "Daniel Gomez",
    email_address: "danielgomez@example.com",
    mailing_address: "505 Cedar Ln",
    phone_number: "+1-555-0123",
    billing_address: "505 Cedar Ln",
  },
  {
    username: "meganharris",
    password: "megan456",
    is_admin: false,
    name: "Megan Harris",
    email_address: "meganharris@example.com",
    mailing_address: "606 Elm St",
    phone_number: "+1-555-1234",
    billing_address: "606 Elm St",
  },
  {
    username: "johnsmith",
    password: "john987",
    is_admin: false,
    name: "John Smith",
    email_address: "johnsmith@example.com",
    mailing_address: "707 Fir Rd",
    phone_number: "+1-555-2345",
    billing_address: "707 Fir Rd",
  },
  {
    username: "susanwilson",
    password: "susan112",
    is_admin: false,
    name: "Susan Wilson",
    email_address: "susanwilson@example.com",
    mailing_address: "808 Maple Ave",
    phone_number: "+1-555-3456",
    billing_address: "808 Maple Ave",
  },
  {
    username: "matthewtaylor",
    password: "matt1234",
    is_admin: false,
    name: "Matthew Taylor",
    email_address: "matthewtaylor@example.com",
    mailing_address: "909 Oak Ln",
    phone_number: "+1-555-4567",
    billing_address: "909 Oak Ln",
  },
  {
    username: "karenmoore",
    password: "karen321",
    is_admin: false,
    name: "Karen Moore",
    email_address: "karenmoore@example.com",
    mailing_address: "1010 Pine Blvd",
    phone_number: "+1-555-5678",
    billing_address: "1010 Pine Blvd",
  },
  {
    username: "justinlee",
    password: "justin111",
    is_admin: false,
    name: "Justin Lee",
    email_address: "justinlee@example.com",
    mailing_address: "1111 Birch Rd",
    phone_number: "+1-555-6789",
    billing_address: "1111 Birch Rd",
  },
  {
    username: "melissacarter",
    password: "melissa123",
    is_admin: false,
    name: "Melissa Carter",
    email_address: "melissacarter@example.com",
    mailing_address: "1212 Cedar St",
    phone_number: "+1-555-7890",
    billing_address: "1212 Cedar St",
  },
  {
    username: "andrewjackson",
    password: "andrew234",
    is_admin: false,
    name: "Andrew Jackson",
    email_address: "andrewjackson@example.com",
    mailing_address: "1313 Elm Rd",
    phone_number: "+1-555-8901",
    billing_address: "1313 Elm Rd",
  },
  {
    username: "briannaparker",
    password: "brianna456",
    is_admin: false,
    name: "Brianna Parker",
    email_address: "briannaparker@example.com",
    mailing_address: "1414 Oak Blvd",
    phone_number: "+1-555-9012",
    billing_address: "1414 Oak Blvd",
  },
  {
    username: "richardmorris",
    password: "richard789",
    is_admin: false,
    name: "Richard Morris",
    email_address: "richardmorris@example.com",
    mailing_address: "1515 Fir St",
    phone_number: "+1-555-0123",
    billing_address: "1515 Fir St",
  },
  {
    username: "amandawood",
    password: "amanda112",
    is_admin: false,
    name: "Amanda Wood",
    email_address: "amandawood@example.com",
    mailing_address: "1616 Cedar Ln",
    phone_number: "+1-555-1234",
    billing_address: "1616 Cedar Ln",
  },
  {
    username: "brianbaker",
    password: "brian987",
    is_admin: false,
    name: "Brian Baker",
    email_address: "brianbaker@example.com",
    mailing_address: "1717 Birch Blvd",
    phone_number: "+1-555-2345",
    billing_address: "1717 Birch Blvd",
  },
  {
    username: "jenniferadams",
    password: "jennifer321",
    is_admin: false,
    name: "Jennifer Adams",
    email_address: "jenniferadams@example.com",
    mailing_address: "1818 Elm St",
    phone_number: "+1-555-3456",
    billing_address: "1818 Elm St",
  },
  {
    username: "georgeedwards",
    password: "george654",
    is_admin: false,
    name: "George Edwards",
    email_address: "georgeedwards@example.com",
    mailing_address: "1919 Oak Rd",
    phone_number: "+1-555-4567",
    billing_address: "1919 Oak Rd",
  },
  {
    username: "heathergreen",
    password: "heather123",
    is_admin: false,
    name: "Heather Green",
    email_address: "heathergreen@example.com",
    mailing_address: "2020 Pine Blvd",
    phone_number: "+1-555-5678",
    billing_address: "2020 Pine Blvd",
  },
  {
    username: "michaelharris",
    password: "michael234",
    is_admin: false,
    name: "Michael Harris",
    email_address: "michaelharris@example.com",
    mailing_address: "2121 Fir Ln",
    phone_number: "+1-555-6789",
    billing_address: "2121 Fir Ln",
  },
  {
    username: "sharonscott",
    password: "sharon345",
    is_admin: false,
    name: "Sharon Scott",
    email_address: "sharonscott@example.com",
    mailing_address: "2222 Birch Rd",
    phone_number: "+1-555-7890",
    billing_address: "2222 Birch Rd",
  },
  {
    username: "robertjohnson",
    password: "robert567",
    is_admin: false,
    name: "Robert Johnson",
    email_address: "robertjohnson@example.com",
    mailing_address: "2323 Cedar Blvd",
    phone_number: "+1-555-8901",
    billing_address: "2323 Cedar Blvd",
  },
  {
    username: "lindawilson",
    password: "linda678",
    is_admin: false,
    name: "Linda Wilson",
    email_address: "lindawilson@example.com",
    mailing_address: "2424 Pine St",
    phone_number: "+1-555-9012",
    billing_address: "2424 Pine St",
  },
  {
    username: "michaelwhite",
    password: "michael123",
    is_admin: false,
    name: "Michael White",
    email_address: "michaelwhite@example.com",
    mailing_address: "2525 Oak Ln",
    phone_number: "+1-555-0123",
    billing_address: "2525 Oak Ln",
  },
  {
    username: "emilyrichards",
    password: "emily234",
    is_admin: false,
    name: "Emily Richards",
    email_address: "emilyrichards@example.com",
    mailing_address: "2626 Elm Blvd",
    phone_number: "+1-555-1234",
    billing_address: "2626 Elm Blvd",
  },
  {
    username: "danielgarcia",
    password: "daniel345",
    is_admin: false,
    name: "Daniel Garcia",
    email_address: "danielgarcia@example.com",
    mailing_address: "2727 Fir Rd",
    phone_number: "+1-555-2345",
    billing_address: "2727 Fir Rd",
  },
  {
    username: "laurawilson",
    password: "laura456",
    is_admin: false,
    name: "Laura Wilson",
    email_address: "laurawilson@example.com",
    mailing_address: "2828 Birch Ave",
    phone_number: "+1-555-3456",
    billing_address: "2828 Birch Ave",
  },
  {
    username: "thomaslee",
    password: "thomas567",
    is_admin: false,
    name: "Thomas Lee",
    email_address: "thomaslee@example.com",
    mailing_address: "2929 Cedar Ln",
    phone_number: "+1-555-4567",
    billing_address: "2929 Cedar Ln",
  },
  {
    username: "marysanchez",
    password: "mary678",
    is_admin: false,
    name: "Mary Sanchez",
    email_address: "marysanchez@example.com",
    mailing_address: "3030 Pine Rd",
    phone_number: "+1-555-5678",
    billing_address: "3030 Pine Rd",
  },
  {
    username: "williamallen",
    password: "william123",
    is_admin: false,
    name: "William Allen",
    email_address: "williamallen@example.com",
    mailing_address: "3131 Oak Blvd",
    phone_number: "+1-555-6789",
    billing_address: "3131 Oak Blvd",
  },
  {
    username: "oliviaanderson",
    password: "olivia234",
    is_admin: false,
    name: "Olivia Anderson",
    email_address: "oliviaanderson@example.com",
    mailing_address: "3232 Elm Ln",
    phone_number: "+1-555-7890",
    billing_address: "3232 Elm Ln",
  },
  {
    username: "jasonmartinez",
    password: "jason345",
    is_admin: false,
    name: "Jason Martinez",
    email_address: "jasonmartinez@example.com",
    mailing_address: "3333 Birch Blvd",
    phone_number: "+1-555-8901",
    billing_address: "3333 Birch Blvd",
  },
  {
    username: "isabelhernandez",
    password: "isabel456",
    is_admin: false,
    name: "Isabel Hernandez",
    email_address: "isabelhernandez@example.com",
    mailing_address: "3434 Pine St",
    phone_number: "+1-555-9012",
    billing_address: "3434 Pine St",
  },
  {
    username: "patriciagonzalez",
    password: "patricia567",
    is_admin: false,
    name: "Patricia Gonzalez",
    email_address: "patriciagonzalez@example.com",
    mailing_address: "3535 Cedar Blvd",
    phone_number: "+1-555-0123",
    billing_address: "3535 Cedar Blvd",
  },
  {
    username: "matthewrodgers",
    password: "matthew678",
    is_admin: false,
    name: "Matthew Rodgers",
    email_address: "matthewrodgers@example.com",
    mailing_address: "3636 Oak Rd",
    phone_number: "+1-555-1234",
    billing_address: "3636 Oak Rd",
  },
  {
    username: "shelleywilliams",
    password: "shelley789",
    is_admin: false,
    name: "Shelley Williams",
    email_address: "shelleywilliams@example.com",
    mailing_address: "3737 Elm Blvd",
    phone_number: "+1-555-2345",
    billing_address: "3737 Elm Blvd",
  },
  {
    username: "davidgonzales",
    password: "david123",
    is_admin: false,
    name: "David Gonzales",
    email_address: "davidgonzales@example.com",
    mailing_address: "3838 Birch Rd",
    phone_number: "+1-555-3456",
    billing_address: "3838 Birch Rd",
  },
  {
    username: "lindabrown",
    password: "linda234",
    is_admin: false,
    name: "Linda Brown",
    email_address: "lindabrown@example.com",
    mailing_address: "3939 Pine Ln",
    phone_number: "+1-555-4567",
    billing_address: "3939 Pine Ln",
  },
  {
    username: "robertsmith",
    password: "robert345",
    is_admin: false,
    name: "Robert Smith",
    email_address: "robertsmith@example.com",
    mailing_address: "4040 Cedar Blvd",
    phone_number: "+1-555-5678",
    billing_address: "4040 Cedar Blvd",
  },
  {
    username: "lisagreen",
    password: "lisa456",
    is_admin: false,
    name: "Lisa Green",
    email_address: "lisagreen@example.com",
    mailing_address: "4141 Oak Rd",
    phone_number: "+1-555-6789",
    billing_address: "4141 Oak Rd",
  },
];

export { usersToCreate };